### DISCUSSION TITLE
chekcout to pipeline source commit using `steps.checkout`.

### DISCUSSION THREAD

**Discussion by lesomnus** [microsoft/azure-pipelines-agent#4428] [Ideas]
Assuome the repo `B` depending on the repo `A` as a submodule at `external/A`.
Consider following `pipelines.yaml`:
```yaml
resources:
  repositories:
    - repository: A
      type: git
      name: A

  pipelines:
    - pipeline: A-CI
      source: A
      trigger:
        branches:
          include:
            - main
            - devel

jobs:
  - job: Build
    uses:
      repositories:
        - A
       
    steps:
      - checkout: self
        submodules: true

      - checkout: A
        path: external/A
```
This pipeline will be triggered when the pipline `A` is completed and in this pipeline, `B`, want to test if it can be built with the latest commit of `A` (which is just pass the pipeline `A`).
At this time, `A/main` will be checked out that is not what we want.

It would be nice if we can:
```yaml
    steps:
      - ...

      # It will checkout to A@$(resources.pipeline.A-CI.sourceCommit)
      - checkout: A-CI
        path: external/A
        condition: eq(variables['Build.Reason'], 'ResourceTrigger')
```

Alternatively, we can check out to the commit we want to by manual:
```yaml
- script: |
    cd external/A && git fetch && git checkout $(resources.pipeline.A.sourceCommit)
  condition: eq(variables['Build.Reason'], 'ResourceTrigger')
```
But this requires to the credential be remain after checkout using `checkout.persistCredentials` and it does not work with the submodules at this time. #4295 #4114
