### DISCUSSION TITLE
Is duplicated `jobs.job` safe?

### DISCUSSION THREAD

**Discussion by lesomnus** [microsoft/azure-pipelines-agent#4442] [Q&A]
I use following `azure-pipelines.yaml` :
```yaml
 - Agent.OSArchitecture -equals X64

stages:
  - stage: Build
    ...
    jobs:
      ...
      - ${{ each reference in parameters.references }}:
          - job: Build
            displayName: Build ${{ reference }}
            container:
              image: thordrive/docker:24
              mapDockerSocket: false
              options: >-
                --privileged
```
It works; multiple jobs are run in parallel as I expected but the job ID, "Build", is duplciated.
Now I want to depend on the "Build" jobs at last job. Can I depend on "Build"? Does it waits all "Build" jobs? Is this intended behavior?
