### ISSUE TITLE
Yaml Builds specified for Default queue run in Hosted VS2017

### ISSUE THREAD

**Issue by jwittner** [Microsoft/azure-pipelines-agent#1518]
Are we accepting PRs against the preview docs?

```
queue: Default
```

results in builds running in `Hosted VS2017` while

```
queue:
  name: Default
```

runs the builds in `Default`.

[The docs](https://github.com/Microsoft/vsts-agent/blob/a86ddbda8d36d4768b8590a69d465a9808b06adc/docs/preview/yamlgettingstarted-queues.md) refer to the former failing example.

**Comment by ericsciple** [comment]
the docs are correct. it's possible something has regressed on the service, although we haven't had any other reports. I'll try to repro

**Comment by jwittner** [comment]
I saw somewhere else in the docs, the latter example, and it fixed my problem. I'll have to search my history.

**Comment by jwittner** [comment]
We're continuing to see strangeness around this. Several new builds (using the latter examples above) create definitions that incorrectly build on Hosted VS 2017. We have to go in and modify the queue to Default manually.

**Comment by jwittner** [comment]
Is this the best place for this issue? Or is there a better repo I should migrate it to? Starting to seem like a VSTS back end issue with less to do with the vsts-agent.

**Comment by ericsciple** [comment]
I think the experience is causing confusion. The queue defined on the definition in the web is the fallback, for any phases in your file that do not specify a queue.

**Comment by jwittner** [comment]
I have 
```
queue:
  name: Default
```
at the very top of the `.vsts-ci.yml` file, when I push that to VSTS it creates a build definition. Builds triggered for that definition are running in `Hosted VS2017`. That's expected behavior?

**Comment by ericsciple** [comment]
That is not expected. I am also not able to reproduce that behavior. Here is what I tried:

1. Create a new repo
2. Create a file `.vsts-ci.yml` with the following content:
```yaml
phases:
# This phase uses the Hosted Linux Preview queue
- phase: linux
  queue: Hosted Linux Preview
  steps:
  - script: pwd

# This phase falls back to the queue specified on the definition
- phase: windows
  steps:
  - script: cd
```
3. Confirmed the `linux` phase is running on Linux and `windows` is running on Windows (output from `pwd` is `/opt/vsts/work/1/s` and output from `cd` is `D:\a\1\s`)

I also tried this:

1. Create a new repo
2. Create a file `.vsts-ci.yml` with the following content:
```yaml
queue: Hosted Linux Preview
steps:
- script: pwd
```
3. Confirmed the `linux` phase is running on Linux (output from `pwd` is `/opt/vsts/work/1/s`)
