### ISSUE TITLE
Unable to pass multiple Template Parameters to Task

### ISSUE THREAD

**Issue by lucas-natraj** [Microsoft/azure-pipelines-agent#1589]
I've been playing with [Template Files](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-templates.md) and haven't been able to find a way to pass multiple parameters as arguments to a task.

Here's a simple setup -
```
# build.yaml

resources:
- repo: self
  clean: true

phases:
- phase: phase_1
  queue:
    name: my_queue

  steps:
  - template: component.yaml
    parameters:
      component: one
      configuration: debug
```

```
# component.yaml

parameters:
  component: '-skip-'
  configuration: release

steps:

- task: PowerShell@1
  displayName: "setup"
  inputs:
    scriptType: inlineScript
    arguments: ${{ parameters.component }} ${{ parameters.configuration }}     #  <---- problem
    inlineScript: |
      $component = $args[0]
      $configuration = $args[1]
      Write-Host "##vso[task.setvariable variable=MY_COMPONENT]$component"
      Write-Host "##vso[task.setvariable variable=MY_CONFIGURATION]$configuration"

- task: PowerShell@1
  displayName: "environment"
  inputs:
    scriptType: inlineScript
    inlineScript: 'Get-ChildItem Env:'
```

I haven't found any way to pass BOTH `parameters.component` & `parameters.configuration` as arguments. I've tried adding quotes, but nothing seems to work.

Is this supported?

(somewhat related to #1498)

**Comment by TingluoHuang** [comment]
@lucas-natraj try `${{ format('{0} {1}', parameters.component, parameters.configuration }}`

**Comment by lucas-natraj** [comment]
@TingluoHuang yeah, I saw this posted on #1686 and was able to proceed.
Not sure if this is the expected way of solving this or whether y'all are planning on a more streamlined approach in future.
Either way I'm happy to close the issue or leave it open.
Thanks again!

**Comment by TingluoHuang** [comment]
We have created a new repository for all YAML related issues, please move the current issue to there.
https://github.com/Microsoft/azure-pipelines-yaml

**Comment by ericsciple** [comment]
@lucas-natraj when the next sprint rolls out, you will be able to do this:

```yaml
# component.yaml

parameters:
  component: '-skip-'
  configuration: release

steps:

- task: PowerShell@1
  displayName: "setup"
  inputs:
    scriptType: inlineScript
    inlineScript: |
      $component = $args[0]
      $configuration = $args[1]
      Write-Host "##vso[task.setvariable variable=MY_COMPONENT]${{ parameters.component }}"
      Write-Host "##vso[task.setvariable variable=MY_CONFIGURATION]${{ parameters.configuration }}"
```

It will start rolling out after next week, and will take about three weeks to finish rolling out to all accounts.
