### ISSUE TITLE
Exported YAML not valid - "Unexpected value 'condition'"

### ISSUE THREAD

**Issue by simonvane** [Microsoft/azure-pipelines-agent#1673]
## Have you tried trouble shooting?
yes

## Agent Version and Platform
Hosted VS2017

## VSTS Type and Version
VisualStudio.com 

## What's not working?
When build definition is exported using "View YAML" the following is included:

```
queue:
  name: Hosted VS2017
  condition: succeeded()
  demands: 
  - Cmd
  - DotNetFramework
  - vstest
  - java
```

If I try to create a build using the exported yaml this results in the following error: "Unexpected value 'condition'"

Removing "condition: succeeded()" resolves the problem with no ill effects.

Exported YAML should be valid.
