### ISSUE TITLE
Git checkout submodule in YAML

### ISSUE THREAD

**Issue by riezebosch** [Microsoft/azure-pipelines-agent#1729]
It's currently not part of the [yaml options](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-checkout.md).

**Comment by ericsciple** [comment]
This is deployed to some accounts. The deployment will likely reach the rest of the accounts next week.

Docs haven't merged yet. The syntax will be:

```yaml
- checkout: self
  submodules: true
```

**Comment by riezebosch** [comment]
❌ .vsts-ci.yml (Line: 3, Col: 3): Unexpected value 'submodules'

**Comment by TingluoHuang** [comment]
```yaml
steps:
- checkout: self
  submodules: true
```

or 

```yaml
resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

steps:
- checkout: self

```
