### ISSUE TITLE
Git (with authentication) behaves differently in YAML builds

### ISSUE THREAD

**Issue by dalemyers** [Microsoft/azure-pipelines-agent#1833]
With the older style of build definitions, there was an option: "Allow scripts to access the OAuth token". This is no longer required with YAML builds. As far as I can see, the token is just always available via `$(system.accesstoken)`/`$SYSTEM_ACCESSTOKEN`. 

However, it seems to behave differently when it comes to git. 

If you set up a new build definition (old style) with that option checked (and `system.prefergit` set to `true`, although I'm not sure how relevant this still is), you can run commands such as:

```
git checkout master
touch new_file
git add new_file
git commit -m "Added new file"
git push origin master
```

This will just work. 

However, if you do the same thing after switching to a YAML build, this is not the case. 

Issue #1827 and #1582 both outline potential fixes for this. However, this requires active changes. That shouldn't be necessary to port a built to YAML. Furthermore, if a task from an extension uses this pre-existing functionality, they will no longer work with YAML, and this is the case for us. 

What can we do to get git behaving as it did previously without requiring changes to the tasks we use?

**Comment by bryanmacfarlane** [comment]
Allowing the OAuth token is always on in YAML.  You need to format the token into the env block.  Because that's explicit, there's no need for the explicit checkbox.

Marking as a doc issue for follow up.

**Comment by dalemyers** [comment]
I understand that there's no need for the explicit checkbox. What I'm saying is that this breaks existing tasks and scripts when migrating to YAML.

**Comment by vtbassmatt** [comment]
What Bryan's saying is that the checkbox is replaced by the act of explicitly mapping in the access token.

```yaml
variables:
  system.accesstoken: $( System.AccessToken )
steps:
- task: mytask@1
  ...
```

It's actually more flexible than the checkbox. The checkbox applies to the whole job, but in YAML, you can scope it to a task or script:

```yaml
steps:
- task: mytask@1  # This task has access to the token
  env:
    system.accesstoken: $( System.AccessToken )
- task: myothertask@1  # This task does not
```

I'm updating the docs to reflect this.
