### ISSUE TITLE
Confusion about the timeoutInMinutes value for a task

### ISSUE THREAD

**Issue by dalemyers** [Microsoft/azure-pipelines-agent#1849]
I've set the `timeoutInMinutes` for a task like so:

```
- bash: |
    $(bin_path)/distribute.py
  timeoutInMinutes: 180
  displayName: Distribute
```

Based on the documentation I've found [here](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md#tab/yaml) I'd expect this task to be allowed to continue for 180 minutes before being killed. Instead, we are seeing it killed after 60 minutes. As far as I can tell, it's because the cancel timeout for the _phase_ is set to it's default 60 minutes. Note: We do not set the timeout for the phase explicitly. 

If we need to set the phase timeout to be the sum of the timeouts for all tasks in it, that would be useful to have in the documentation. 

If we don't (which seems like the more sensible solution) then where are we going wrong?

**Comment by TingluoHuang** [comment]
phase default timeout is 60 mins. step default timeout is infinity until the current phase hitting timeout.

So, you need to increase your phase timeout first if you know your task is going to run more than an hour.

We will improve the doc.

**Comment by dalemyers** [comment]
`timeoutInMinutes` doesn't seem to be a valid property on a phase. i.e. this is wrong:

```
- phase: Whatever
  queue:
    name: Something
  timeoutInMinutes: 100
  steps:
  - whatever
```

**Comment by ericsciple** [comment]
Move the property under queue.

Note, we went through a schema rename to simplify concepts (although we held compat for existing customers). So the new syntax is:
```yaml
jobs:
- job: Whatever
  pool: Something
  timeoutInMinutes: 100
  steps:
  - whatever
```

Or using the old syntax:
```yaml
- phase: Whatever
  queue:
    name: Something
    timeoutInMinutes: 100
  steps:
  - whatever
```
