### ISSUE TITLE
Github-Repository-Resource Service Connection Issue

### ISSUE THREAD

**Issue by JeremyTCD** [Microsoft/azure-pipelines-agent#1902]
## Have you tried trouble shooting?
Yes

## VSTS Type and Version
VisualStudio.com

## Account Name
http://jeremytcd.visualstudio.com

## What's not working?
I'm having a service connection issue when attempting to use a Github repository as a resource. I am aware of the advisory [Troubleshoot Azure Resource Manager service connections](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=vsts) and I've read through all of the information on repository resources and service connections I could find ([article 1](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=example#type), [article 2](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories), [article 3](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=vsts#sep-github)). I could not resolve my issue, so I created reproduction repositories:

### [IssueReproduction.RepositoryResource.Template](https://github.com/JeremyTCD/IssueReproduction.RepositoryResource.Template)

This repository has a single file, `template.yml`, with the following contents:

```yaml
jobs:
- job: Test
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo success
```

### [IssueReproduction.RepositoryResource.Consumer](https://github.com/JeremyTCD/IssueReproduction.RepositoryResource.Consumer)

This repository has a single file, `consumer.yml`, with the following contents:

```yaml
resources:
  repositories:
  - repository: templates
    type: github
    name: JeremyTCD/IssueReproduction.RepositoryResource.Template
    endpoint: https://github.com/JeremyTCD/IssueReproduction.RepositoryResource.Template.git

jobs:
- template: template.yml@templates
```

It adds the template repository as a resource using the method documented [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories) and uses `template.yml`. 

### Pipeline
After creating those repositories, I created a pipline - [IssueReproduction.RepositoryResource.Consumer-CI](https://jeremytcd.visualstudio.com/IssueReproduction.RepositoryResource.Consumer/_build?definitionId=5).

Note, initially, `consumer.yml` had no endpoint option, as per the documentation. Without it, I got these 
errors:

```
Repository templates requires an endpoint

Parameter name: endpoint,Unable to cast object of type 'Microsoft.TeamFoundation.DistributedTask.Pipelines.Yaml.Templates.JobsTemplateReference' to type 'Microsoft.TeamFoundation.DistributedTask.Pipelines.Yaml.Templates.Job'.
```

The documentation might need updating with regard to endpoint being required.  

With the endpoint, I get these errors:

```
Repository templates references endpoint https://github.com/JeremyTCD/IssueReproduction.RepositoryResource.Template.git which does not exist or is not authorized for use

Unable to cast object of type 'Microsoft.TeamFoundation.DistributedTask.Pipelines.Yaml.Templates.JobsTemplateReference' to type 'Microsoft.TeamFoundation.DistributedTask.Pipelines.Yaml.Templates.Job'.
```

Here is an example build result: [result](https://jeremytcd.visualstudio.com/IssueReproduction.RepositoryResource.Consumer/_build/results?buildId=32&view=results).

### What I've tried
I noticed that tasks accept service connection options, like `azureSubscription`. The documentation does not specify any equivalent for repositories. I tried random stuff like `githubSubscription` but nothing worked.  

Some Github issues, such as [this one](https://github.com/Microsoft/azure-pipelines-agent/issues/1809#issuecomment-428387295) suggested stuff like adding variables and switching branches. These seem to apply more for when `.yml`s are changed after their initial loading. I tried them anyway and nothing worked.  

I've checked my pipeline's service connections. Since the root repository is also on Github, `Get Sources` already has a valid service connection to Github. I'm not sure if this connection is used for all jobs. Regardless, I could not find any way to add a service connection "for the entire pipline".

**Comment by TingluoHuang** [comment]
@JeremyTCD https://github.com/Microsoft/azure-pipelines-yaml is the new repository for all yaml related question moving forward.

you need to create a github endpoint like this:
![image](https://user-images.githubusercontent.com/1750815/47367953-b5599280-d6ae-11e8-9636-a91b6ffe13ef.png)

```yaml
resources:
  repositories:
  - repository: templates
    type: github
    name: JeremyTCD/IssueReproduction.RepositoryResource.Template
    endpoint: <name you give when create the endpoint>

jobs:
- template: template.yml@templates
```

**Comment by JeremyTCD** [comment]
@TingluoHuang Thanks for the quick response!

> https://github.com/Microsoft/azure-pipelines-yaml is the new repository for all yaml related question moving forward.

Okay, would be helpful if this was noted in the ReadMe for this repository.

The fix worked, though the documentation [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#repository) needs to be fixed:

``` yml
resources:
  repositories:
  - repository: string  # identifier (no spaces allowed)
    type: enum  # see below
    name: string  # repository name (format depends on `type`)
    ref: string  # ref name to use, defaults to 'refs/heads/master'
    endpoint: string  # endpoint for a GitHub repository
```

I've opened a separate issue in the docs repository, will update it.
