### ISSUE TITLE
[Solved][Question] Set and use an encrypted environment variable

### ISSUE THREAD

**Issue by kittaakos** [Microsoft/azure-pipelines-agent#1982]
Is it possible to set and use an encrypted `GH_TOKEN`/`GITHUB_TOKEN` environment variable with a personal OAuth token for GH? It is fairly straightforward for [Travis CI](https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings) and [AppVeyor](https://www.appveyor.com/docs/build-configuration/#secure-variables) too.

It would be used by, for instance, the [electron-builder](https://github.com/vuetifyjs/electron/blob/master/docs/en/using-electron-builder.md#setting-up-travis-ciappveyor) and also it is a nice to have for [`vscode-ripgrep`](https://github.com/Microsoft/vscode/issues/28434#issuecomment-346199674) to avoid `Error: API rate limit exceeded`.

If this is possible, can someone please share a link to a sample configuration?

I would like to achieve the followings:
 - check out another private GitHub repository as part of the pipeline build,
 - use a private NPM registry during my build and publish there (`yarn publish --no-git-tag-version` could help though), and
 - deploy a new electron release to GH.

Thank you!

----
Solution:

1. Select your pipeline.
2. Click on `Edit`.
![screen shot 2018-11-21 at 17 00 54](https://user-images.githubusercontent.com/1405703/48853566-13fa5500-edb0-11e8-8553-148d1d1415e9.jpg)
3. Click on `Variables`.
![screen shot 2018-11-21 at 17 01 11](https://user-images.githubusercontent.com/1405703/48853595-1e1c5380-edb0-11e8-90a1-65759d57d9f8.jpg)
4. Define your variable. Make sure it is not a plain text.
![screen shot 2018-11-21 at 17 01 40](https://user-images.githubusercontent.com/1405703/48853634-37250480-edb0-11e8-857d-54de181340dc.jpg)

`azure-pipelines.yml`:
```yml
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: mkdir foo && cd foo && git init && git pull https://$GH_TOKEN@github.com/nameOrOrganization/repositoryName.git && ls -al
  displayName: 'Clone with a predefined GitHub OAuth token'
  env:
     GH_TOKEN: $(gh.token)

```
