### ISSUE TITLE
[question] Downloadable artifacts with `PublishBuildArtifacts`, `DownloadBuildArtifacts`, and `CopyFiles`

### ISSUE THREAD

**Issue by kittaakos** [Microsoft/azure-pipelines-agent#1985]
It's a question.

## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
👍 

## Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...

OS of the machine running the agent? OSX/Windows/Linux/...
All. macOS and Windows to build, Linux to publish.

## VSTS Type and Version
On-Prem TFS

I would like to set up two separate jobs (one for macOS and one for Windows). Each job builds an electron artifact into the `./electron/dist/` folder. Windows will produce `MyProduct-0.0.1-win.zip` and the OS X one creates the `MyProduct-0.0.1-dmg`. How can one download the two artifacts?

![screencast 2018-11-26 17-18-46](https://user-images.githubusercontent.com/1405703/49027043-95caf380-f19f-11e8-92f3-d0bb1c8d63cc.gif)

Is there an example which I could use? I looked into the [Batch Explorer](https://github.com/Azure/BatchExplorer) electron application too, sadly it does not use the YAML configuration to build and publish the electron application.

I have tried to use the following examples without luck:
  - https://github.com/fastpack/fastpack/blob/e33b456e27d0511e40b66cd450182e544f7040b0/azure-pipelines.yml#L62-L89
 - http://dontcodetired.com/blog/post/Azure-Functions-Continuous-Deployment-with-Azure-Pipelines-Part-3-Creating-an-Initial-Build-Pipeline
 - https://github.com/MicrosoftDocs/vsts-docs/issues/1934#issuecomment-439028346

My configuration looks like this. Yes; it's a mess. Any help is appreciated, thank you!
```yml
trigger:
  batch: true
  branches:
    include:
    - master

pr:
- master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: mkdir -p dist/mac && cd dist/mac && echo > empty-mac.txt && ls -al
    condition: and(succeeded(), eq(variables['agent.os'], 'Darwin'))
    displayName: 'Build (macOS)'
  - task: CopyFiles@2
    inputs:
      contents: empty-mac.txt
      targetFolder: $(Build.SourcesDirectory)/dist/mac
    condition: and(succeeded(), eq(variables['agent.os'], 'Darwin'))
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: MyBuildOutputs
    condition: and(succeeded(), eq(variables['agent.os'], 'Darwin'))

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: mkdir dist\\win && cd dist\\win && echo>empty-win.txt && dir
    condition: and(succeeded(), eq(variables['agent.os'], 'Windows_NT'))
    displayName: 'Build (Windows)'
  - task: CopyFiles@2
    inputs:
      contents: empty-win.txt
      targetFolder: $(Build.SourcesDirectory)/dist/win
    condition: and(succeeded(), eq(variables['agent.os'], 'Windows_NT'))
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: MyBuildOutputs
    condition: and(succeeded(), eq(variables['agent.os'], 'Windows_NT'))

- job: Publish
  dependsOn:
  - macOS
  - Windows
  condition: succeeded()
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: PublishBuildArtifacts@1
    displayName: 'Publish end to end test artifact'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
      artifactName: dist
```

**Comment by TingluoHuang** [comment]
@kittaakos i think i get your question, maybe not :)
checkout the yaml file used for release the agent in this repository: https://github.com/Microsoft/azure-pipelines-agent/blob/master/.vsts.release.yml

we build `win-x64` `win-x86` `linux-x64` `linux-arm` `osx-x64` in parallel jobs, and each of them will produce a `zip` or `tar.gz`. the final job will depends on the previous 5 jobs and pull down all 5 packages that upload by previous jobs and create github release with those files.

**Comment by kittaakos** [comment]
> @kittaakos i think i get your question, maybe not :)
> checkout the yaml file used for release the agent in this repository: https://github.com/Microsoft/azure-pipelines-agent/blob/master/.vsts.release.yml

Thanks for the hint, @TingluoHuang! I come back either with a simplified YAML setup as a possible solution or with a follow-up question.

**Comment by kittaakos** [comment]
I meant a simple "download" functionality instead of a full publishing but that is my next step, so it's a good example.

If you would like to simply keep the build artifacts with the builds and have a download link to them, you can do this:

```yml
trigger:
  batch: true
  branches:
    include:
    - master

pr:
- master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: mkdir -p dist/mac && cd dist/mac && echo > empty-mac.txt
    displayName: 'Dummy Build'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: dist/mac/empty-mac.txt
      artifactName: 'empty-mac.txt'
    displayName: 'Publis Build'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: mkdir dist\\win && cd dist\\win && echo > empty-win.txt
    displayName: 'Dummy Build'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: dist/win/empty-win.txt
      artifactName: 'empty-win.txt'

```
![screencast 2018-11-26 19-19-11](https://user-images.githubusercontent.com/1405703/49037256-0b43bd80-f1ba-11e8-844b-e6a0a122a163.gif)
