### ISSUE TITLE
[question] Publish a ZIP archive with the `PublishBuildArtifacts@1` task

### ISSUE THREAD

**Issue by kittaakos** [Microsoft/azure-pipelines-agent#1986]
When I use the `PublishBuildArtifacts` task to publish a resource which is a ZIP then I have a ZIP inside a ZIP when I want to download it. Is there a way to avoid zipping the artifact when downloading if it is already in the ZIP format?

![screen shot 2018-11-27 at 11 59 43](https://user-images.githubusercontent.com/1405703/49077713-4d154800-f23c-11e8-8a2a-826f055f9e38.jpg)

`azure-pipelines.yml`:
```yml
trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: mkdir -p dist/mac && cd dist/mac && echo > empty-mac.txt && zip empty-mac.zip empty-mac.txt
    displayName: 'Dummy Build'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: dist/mac/empty-mac.zip
      artifactName: 'empty-mac.zip'
    displayName: 'Publis Build'
```

**Comment by TingluoHuang** [comment]
@kittaakos unfortunately, the server is not smart enough to avoid the double `zip`, and i think we might not able to change this since existing customer may has script/automation tool that take dependency on this `double zip` behavior.

**Comment by kittaakos** [comment]
Thank you, @TingluoHuang.

As a workaround, one can use the [`ExtractFiles@1`](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/extract-files?view=vsts) task to overcome this limitation.

```yml
trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: mkdir -p dist/mac && cd dist/mac && echo > empty-mac.txt && zip empty-mac.zip empty-mac.txt
    displayName: 'Dummy Build - Let assume this is a blackbox and it always produces a ZIP.'
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: 'dist/mac/empty-mac.zip' 
      destinationFolder: dist/mac/empty-mac
      cleanDestinationFolder: true 
    displayName: 'Unzipping Build Artifact - Workaround for https://github.com/Microsoft/azure-pipelines-agent/issues/1986'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: dist/mac/empty-mac
      artifactName: 'empty-mac'
    displayName: 'Publis Build'
```

----

> and i think we might not able to change this since existing customer may has script/automation tool that take dependency on this `double zip` behavior.

Noted. I am closing this. Please reopen if required.
