### ISSUE TITLE
Provide a task/command in agent/config.sh to exit build agent after this job

### ISSUE THREAD

**Issue by jstevans** [microsoft/azure-pipelines-agent#1997]
[Also posted on Azure DevOps Developer Community](https://developercommunity.visualstudio.com/content/idea/394162/provide-a-taskcommand-in-agentconfigsh-to-exit-bui.html)

I want to self-host my build agents in containers, and have each build create new containers at the beginning of the pipeline and destroy them at the end of each job in the pipeline. To ensure that I don't get into a race where a new build might end up running on containers created by another build before that build can cleanup, I want a build job to be able to to tell its build agent to gracefully exit after the current job completes.

I've tried using `/agent/config.sh remove`, but regardless of attempts to sleep, background, etc. It seems to always fail with an error that the agent is busy with a job. It would be nice if I could do `config.sh remove --afterCurrentJob` or something along those lines.

Example:
```yaml
phases:
- phase: Phase_1
  displayName: Create container instance
  condition: succeeded()
  server: true
#Task group has not been exported, task groups are not supported yet


- phase: Phase_2
  displayName: Build Phase
  condition: succeeded()
  queue:
    name: test-johnst
  - task: Gulp@0
    displayName: 'gulp build -p'
    inputs:
      targets: build
      arguments: '-p'
    enabled: true
  - script: |  
       ./config.sh remove --after-current-task --unattended --auth pat --token $(my_pat)
    displayName: 'Command Line Script'
    condition: always()
```
