### ISSUE TITLE
[question] Publish Test Results task: Could not publish build level data. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by kittaakos** [Microsoft/azure-pipelines-agent#2020]
I have two pipeline jobs, one for macOS and one for Windows. Both jobs invoke the same template file which contains the followings:

```yml
- script: myFolder/gradlew -p ./myFolder/ clean build -PignoreTestFailures=true --refresh-dependencies --continue
  displayName: 'Gradle - Build'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/build/test-results/test/*.xml'
    mergeTestResults: true
    testRunTitle: 'Tests'
  displayName: 'Publish - Test Results'
```
The macOS build runs first, no warnings. Then I can see the following warning in the Windows log:
```
##[warning]Could not publish build level data. Object reference not set to an instance of an object.
```

Question: What does it mean? What is the problem?
Note: I am not using any Gradle Tools task.

Thank you!
