### ISSUE TITLE
Using expressions in a GitHub Release task

### ISSUE THREAD

**Issue by kittaakos** [Microsoft/azure-pipelines-agent#2023]
Can I use expressions in a GH release task? I want to achieve something like this:

```yml
- task: GithubRelease@0
  inputs:
    # Imaginre the mandatory inputs here...
    tag: $(Release.Tag)
    isDraft: ne(variables['Release.IsDraft'], 'false')
    addChangeLog: eq(variables['Release.AddChangeLog'], 'true')
  condition: and(succeeded(), startsWith(variables['Release.Tag'], 'v'))
```

I ran [my pipeline build](https://dev.azure.com/kittaakos/first-test/_build/results?buildId=209) with the following queue time variables:
```
system.debug true
agent.diagnostic true
Release.Tag v1.2.3
Release.AddChangeLog true
Release.IsDraft xxx
```

I thought:
 - `isDraft` will evaluate to `true` (because `xxx` is not equal to `false`) and
 - `addChangeLog` will be `true` but I must be missing something because my GH release ended up as the latest releases (instead of a draft one) without the changelog.

<img width="773" alt="screen shot 2018-12-18 at 23 08 47" src="https://user-images.githubusercontent.com/1405703/50186054-f7ebc400-0319-11e9-80a6-bd2661d8628d.png">

According to the [`Tasks/GitHubReleaseV0/task.json`](https://github.com/Microsoft/azure-pipelines-tasks/blob/c049ea27df33548f71d4b9b1ca3be6b0f191c44b/Tasks/GitHubReleaseV0/task.json), both [`isDraft`](https://github.com/Microsoft/azure-pipelines-tasks/blob/a2e7c80104dc4b0dbb4e301f19bea7e2c0f93704/Tasks/GitHubReleaseV0/task.json#L155-L156) and [`addChangeLog`](https://github.com/Microsoft/azure-pipelines-tasks/blob/a2e7c80104dc4b0dbb4e301f19bea7e2c0f93704/Tasks/GitHubReleaseV0/task.json#L173-L174) are declared with `boolean` type.

Is this a missing feature, a bug, or I made the mistake again? I can see these in the pipeline log:
```
2018-12-18T21:36:35.1537648Z ##[debug]isDraft=ne(variables['Release.IsDraft'], 'false')
...
2018-12-18T21:36:35.1549680Z ##[debug]changeLog=eq(variables['Release.AddChangeLog'], 'true')
```

Thank you!

**Comment by TingluoHuang** [comment]
@kittaakos  i don't think you need to use expression for this.
all task inputs are just string, task author use task.json to tells UI how to render it.
I think the following should just work
```
- task: GithubRelease@0
  inputs:
    # Imaginre the mandatory inputs here...
    tag: $(Release.Tag)
    isDraft: $(Release.IsDraft)
    addChangeLog: $(Release.AddChangeLog)
  condition: and(succeeded(), startsWith(variables['Release.Tag'], 'v'))
```
```
Release.IsDraft=true
Release.AddChangeLog
```
