### ISSUE TITLE
VSCode extension, which includes a local server, tests

### ISSUE THREAD

**Issue by peni4142** [Microsoft/azure-pipelines-agent#2059]
## Having an issue with software on Hosted Agent?
VSCode extension tests as described in the docs https://code.visualstudio.com/api/working-with-extensions/testing-extension.

That means among other things Electron and NodeJs are included.

## Agent Version and Platform
I don't know how to get information about the versions but that is the yml definition for the agents I tried:

```
jobs:

- template: ./test.yml  
  parameters:
    name: Linux
    pool: Hosted Ubuntu 1604
#     # pool: Hosted Linux Preview seems not available


- template: ./test.yml  
  parameters:
    name: macOS
    pool: Hosted macOS

- template: ./test.yml  
  parameters:
    name: Windows1
    pool: Hosted VS2017

- template: ./test.yml  
  parameters:
    name: Windows2
    pool: Hosted

- template: ./test.yml  
  parameters:
    name: Windows3
    pool: Hosted Windows Container


```
(last run today 16.01.2019)

## What's not working?

Send a request to a local server :

```
this.configServer = createServer((req: IncomingMessage, res: ServerResponse) => {
                // do some 
            }).listen(6123);
```

Error Message
```
connect ECONNREFUSED 127.0.0.1:6123
Error: connect ECONNREFUSED 127.0.0.1:6123
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

```

And Ubuntu is not working at all. I tried that on my own private Linux(arch) machine. There was the package "libgconf2-4" missing. Maybe that is the same error on the hosted agent, but I don't know, because it returns only the error message "##[error]Bash exited with code '1'."

## Agent and Worker's Diagnostic Logs
Yeah, I don't know where looking for them for a hosted agent... The only logs I find are not that information rich.

An example of the build logs. Not that information-rich
[8_Run tests.txt](https://github.com/Microsoft/azure-pipelines-agent/files/2765013/8_Run.tests.txt)
