### ISSUE TITLE
Trouble with workingDirectory/targetPath on Container Jobs

### ISSUE THREAD

**Issue by dferretti-fig** [Microsoft/azure-pipelines-agent#2100]
I'm trying to use a container job where I copy files to a specific directory outside the source root. (Terraform requires tfplans to be extracted to the same absolute path if moving from agent to agent). My thought was to use a container job, pull my files to something like `/terraform` and work/publish artifacts/extract artifacts from there. Since this is running in a container and this is not a mounted directory I don't have to worry about leaking to the agent's host. However, my bash and PublishPipelineArtifact tasks are failing when I try to set the workingDirectory or targetPath to this directory I've created in an earlier step. 

Example pipeline yml:

```
name: Test
resources:
  containers:
    - container: ubuntu1604
      image: ubuntu:16.04
trigger: none
pr: none
jobs:
  - job: Test
    pool: My Pool
    container: ubuntu1604
    steps:
      - bash: mkdir /mytest && touch /mytest/test.txt
        displayName: Create directory and add file
      # this step works
      - bash: ls /mytest
        displayName: Verify directory and contents still exist from one step to the next
      # this step fails
      - bash: ls
        displayName: Attempt to run bash script with working directory in new folder
        workingDirectory: /mytest
  - job: Test_2
    pool: My Pool
    container: ubuntu1604
    steps:
      - bash: mkdir /mytest && mkdir /mytest/a && touch /mytest/a/test.txt
        displayName: Create directory and add file
      # this step works
      - bash: ls /mytest/a
        displayName: Verify directory and contents still exist from one step to the next
      # this step fails
      - bash: ls
        displayName: Attempt to run bash script with working directory in new folder
        workingDirectory: /mytest/a
  - job: Test_3
    pool: My Pool
    container: ubuntu1604
    steps:
      - bash: mkdir /mytest && mkdir /mytest/a && touch /mytest/a/test.txt
        displayName: Create directory and add file
      # this step works
      - bash: ls /mytest/a
        displayName: Verify directory and contents still exist from one step to the next
      - task: PublishPipelineArtifact@0
        displayName: Publish from new directory
        inputs:
          artifactName: drop
          targetPath: /mytest/a
```

Job 1 and 2 are essentially the same. They use the Bash@3 task which calls `tl.getPathInput` behind the scenes. The only difference in output is Job 1 fails with

```
##[debug]workingDirectory=mytest
##[debug]check path : mytest
##[debug]task result: Failed
##[error]Not found workingDirectory: mytest
```
and Job 2 fails with 

```
##[debug]workingDirectory=a
##[debug]check path : a
##[debug]task result: Failed
##[error]Not found workingDirectory: a
```
I only mention that because I'm not sure why it says the working directory is `a` instead of `/mytest/a`. 

Job 3 which calls the PublishPipelineArtifact which looks like it uses a special extension built into the agent and not a normal node/powershell task. I haven't dug into that source code yet but it fails with:
```
##[error]Path not exist: /mytest/a
##[debug]Processed: ##vso[task.logissue type=error;]Path not exist: /mytest/a
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Agent.Plugins.PipelineArtifact.PublishPipelineArtifactTask.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, String targetPath, String artifactName, CancellationToken token)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
```

At first I was going to put this issue over in https://github.com/Microsoft/azure-pipelines-task-lib because I thought maybe it was a problem with `getPathInput` checking existence at job start or too early or something else, but now that I see the PublishPipelineArtifact also failing I'm thinking maybe it has to do with how container jobs map their agent directories?

Agent version is 2.147.1, running in account figdevteam.visualstudio.com.
