### ISSUE TITLE
git submodule checkout, false value not supported to switch it off but empty string is

### ISSUE THREAD

**Issue by lukeapage** [Microsoft/azure-pipelines-agent#2152]
## Agent Version and Platform
2.148.0 Windows

## Azure DevOps Type and Version
dev.azure.com

## What's not working?

I didn't want to checkout sub modules and false didn't work as a value.

Thankfully your documentation has a comment explaining a bug:

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout

![image](https://user-images.githubusercontent.com/309321/54192058-6d010c80-44b7-11e9-8496-d56700671f46.png)

https://github.com/Microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/GitSourceProvider.cs#L213-L223

either document that you should use an empty string to stop checkout of sub modules, or support false as an option for not checking out sub modules.

**Comment by TingluoHuang** [comment]
@lukeapage thanks for let us know, i think this is a bug, we will fix it and prepare an agent release out.

**Comment by TingluoHuang** [comment]
@lukeapage after a close look, i don't think this is a real bug, but it is something in the product that confuse customer and we should improve that.
the doc:
```yaml
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: boolean  # whether to fetch clean each time
  fetchDepth: number  # the depth of commits to ask Git to fetch
  lfs: boolean  # whether to download Git-LFS files
  submodules: true | recursive  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
  persistCredentials: boolean  # set to 'true' to leave the OAuth token in the Git config after the initial fetch
```
So, if you don't want to checkout submodule, just don't add `submodules: true|recursive` to your checkout step.
ex:
```yaml
- checkout: self
  clean: true
  persistCredentials: true
```

Note:
There might be a designer option get merged in, make sure you have that unchecked.
![image](https://user-images.githubusercontent.com/1750815/54212717-ad618a00-44b9-11e9-8195-23a9a49f30c6.png)

Please let me know if this is not help for your case, i am totally open to make code changes.
