### ISSUE TITLE
Agent doesn't log to console correct

### ISSUE THREAD

**Issue by dza89** [microsoft/azure-pipelines-agent#2154]
## Agent Version and Platform
2.147.1
![AzureDevopsconsoleerror](https://user-images.githubusercontent.com/20373984/54342696-74eab900-463d-11e9-9aeb-f7d1ccc00c5b.png)
![localerror](https://user-images.githubusercontent.com/20373984/54342697-75834f80-463d-11e9-8503-6ef9107efbed.png)

OS of the machine running the agent? OSX/Windows/Linux/...
Windows Server Core 2019

## Azure DevOps Type and Version
dev.azure.com/sos-team

## What's not working?
Script doesn't log to console. In this case I'm running terraform 0.11.11 on Windows, but I've seen the same behaviour on Linux.

Yaml part:
```
steps:
- powershell: |
    terraform init -input=false
    terraform plan -out=tfplan -input=false
  workingDirectory: release/peripherals/aws/terraform
  failOnStderr: false
  continueOnError: false
  displayName: Setup Peripherals
```

I've added a two printscreens, one with the local output when running TF manually on the agent, and one with the output of the console in Azure Pipelines. (Same agent)
The worker log when running this job is also attached. Seems to me that redirection of STDOUT/STDERR isn't correct.

## Agent and Worker's Diagnostic Logs
See Worker_20190313-123824.utc.log

[Worker_20190313-123824.utc.log](https://github.com/Microsoft/azure-pipelines-agent/files/2965440/Worker_20190313-123824.utc.log)
