### ISSUE TITLE
Desired artifacts will not be downloaded if other published artifacts are unchecked

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-pipelines-agent#2224]
## Agent Version and Platform
Version of your agent? 2.150.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/lolinctest (though I reproed it on a second org as well)

## What's not working?
If multiple artifacts are uploaded in a single build and then a release pipeline is instructed to download only one of them, nothing will be downloaded.

1. Create a build pipeline

```yaml
pool:
  name: Hosted VS2017
steps:
- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifactName: drop1
    targetPath: '$(System.DefaultWorkingDirectory)'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifactName: drop2
    targetPath: '$(System.DefaultWorkingDirectory)'
```

2. Create a release pipeline that is linked to the above build. The issue requires no explicit tasks.
3. Run the pipeline

```
==============================================================================
Task         : Download Pipeline Artifact
Description  : Download Pipeline Artifact
Version      : 1.1.0
Author       : Microsoft Corporation
Help         : Download named artifact from a pipeline to a local path.
==============================================================================
Download artifact to: D:\a\r1\a/artifacts/drop2
Information, Minimatch patterns: [**]
Information, Filtered 6 files from the Minimatch filters supplied.
```

4. Note that 'drop2' download 6 files
4. Edit the agent job to only download 'drop2'

![image](https://user-images.githubusercontent.com/1784452/56615622-14a64a00-65e1-11e9-9675-c4d0fc26eabb.png)

5. Run the pipeline

```
==============================================================================
Task         : Download Pipeline Artifact
Description  : Download Pipeline Artifact
Version      : 1.1.0
Author       : Microsoft Corporation
Help         : Download named artifact from a pipeline to a local path.
==============================================================================
Download artifact to: D:\a\r1\a/artifacts/drop2
Information, Minimatch patterns: [drop2/**]
```

6. Note that 'drop2' downloaded zero files instead of 6.
7. Note also that the minimatch pattern is specified only in the latter instance.

So this seems to be an issue with the _use_ of the Download Pipeline Artifact task, and not the task itself.

## Agent and Worker's Diagnostic Logs
I'm not seeing where these logs are, but this issue is pretty easy to repro.
