### ISSUE TITLE
Azure WebApp Deploy - The service connection name 00000000-0000-0000-0000-000000000000 is ambiguous.

### ISSUE THREAD

**Issue by mdmoura** [microsoft/azure-pipelines-agent#2287]
I am trying to deploy an Asp.Net Core Application to Azure WebApp using Azure Devops.

I have the following YAML file:

```
trigger:
- master

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'any cpu'
  version: '0.2.0'

stages:

// Previous Stages - All Working > Build, Test, etc.

- stage: 'Deploy'
  displayName: 'Deploy'
  jobs:
  - job: 'Azure'
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: AzureWebApp@1
        displayName: 'MyApp Deploy'
        inputs:
          azureSubscription: 'MyName'
          appType: 'webApp'
          appName: 'myaspnetcoreapp'
          package: '$(build.artifactstagingdirectory)/myaspnetcoreapp.zip'
          deploymentMethod: 'auto'
```

I have other stages before this one for Build, Test, etc ...

When I remove the Deploy stage all other stages run without any error.

But when I add this last stage and try to deploy it I get the error:

    The service connection name 00000000-0000-0000-0000-000000000000 is ambiguous.

I do not get any other information about the error ...

Am I missing something?
