### ISSUE TITLE
Guidance on testing azure-pipelines.yml and YAML template files?

### ISSUE THREAD

**Issue by myermian** [microsoft/azure-pipelines-agent#2334]
Currently, I don't know of any way of testing our **azure-pipelines.yml** files or our YAML templates other than simply checking in the changes and running a build in Azure DevOps.

I downloaded this repository and I was attempting to utilize the `PipelineParser` class to parse my **azure-pipelines.yml** file. It seems that the `PipelineParser` does not actually parse the azure-pipelines.yml file, but a modified version of it? I couldn't locate the way the **azure-pipelines.yml** file is transformed to conform with what the `PipelineParser` class expects.

One example is that the `PipelineParser` does not support parsing the file if it contains a trigger or the new stages feature. I can't even get past testing a single **azure-pipelines.yml** file, let alone trying to test with a mix of YAML templates:

```
[TestMethod]
public void SampleTest()
{
    var parseOptions = new ParseOptions
    {
        MaxFiles = 10,
        MustacheEvaluationMaxResultLength = 512 * 1024, // 512k string length
        MustacheEvaluationTimeout = TimeSpan.FromSeconds(10),
        MustacheMaxDepth = 5,
    };

    var ymlFile = Path.Combine("YmlFiles", "azure-pipelines.yml");
    CancellationToken agentShutdownToken = new CancellationToken();

    var pipelineParser = new PipelineParser(new PipelineFileProvider(), parseOptions);

    Process process = pipelineParser.LoadInternal(
        defaultRoot: Directory.GetCurrentDirectory(),
        path: ymlFile,
        mustacheContext: null,
        cancellationToken: agentShutdownToken);
}
```

``` yml
stages:
- stage: sample_stage
  displayName: 'Sample Stage'
  dependsOn: []

  jobs:
  - job: sample_job
    displayName: 'Sample Job'
    pool:
      vmImage: ubuntu-16.04
  
    steps:
    - bash: echo "Hello World"
```
-------------------

Here is an example of one of our real templates which I'll want to eventually test out. But, again, I can't even seem to get the parser to work with the basic pipeline file as seen above, so I won't even get to this template file for awhile:

``` yml
# .NET Core Compilation

parameters:
  projects: '**/*.sln'
  sdkversions: ['2.x']

jobs:
- job: dotnet_compilation
  displayName: '.NET Core Compilation'
  pool:
    vmImage: ubuntu-16.04
  
  steps:
  - template: ../steps/debug-info-bash.yml
  - template: ../steps/dotnet-tool-installer.yml
    parameters:
      sdkversion: ${{ parameters.sdkversion }}
  - template: ../steps/dotnet-restore.yml
  - template: ../steps/dotnet-build.yml
    parameters:
      arguments: '-c Debug --no-restore'
```
