### ISSUE TITLE
"skip ci" in commit message not working

### ISSUE THREAD

**Issue by BoazWarshawsky** [microsoft/azure-pipelines-agent#2441]
I am trying to find a way to skip Azure CI via the commit message, when trying the following messages none of them really do the work and skip the CI run:
[skip ci] or [ci skip]
skip-checks: true or skip-checks:true
[skip azurepipelines] or [azurepipelines skip]
[skip azpipelines] or [azpipelines skip]
[skip azp] or [azp skip]
***NO_CI***

**Comment by DotNetSparky** [comment]
For on-prem server, try this:  `***NO_CI***`
(include the asterisks)

The others might only work for Azure DevOps Services (the hosted version), they don't show up in the docs when I switch the filter to "Azure DevOps Server 2019" (https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops-2019)

**Comment by petong** [comment]
I am having the same issue, and from what I have read in #858 placing [skip ci] in a commit message only skips on merge to master and not in a PR run, which is totally bizarro!

**Comment by BoazWarshawsky** [comment]
`***NO_CI***` is not working too

**Comment by jeliasson** [comment]
Until we have a proper fix in place, here is a temporary fix that will skip the script execution if the commit message (`Build.SourceVersionMessage`) contains `skip ci`. Using a variable if the condition is repeated for more scripts. 

```yaml
variables:
    SKIP_CI_FILTER: 'skip ci'

steps:
  - script: sh ./script1.sh
    condition: not(contains(variables['Build.SourceVersionMessage'], variables['SKIP_CI_FILTER']))
```

**Comment by jtpetty** [comment]
@vtbassmatt - Do you have any context here? Is this our recommended solution?

**Comment by vtbassmatt** [comment]
I believe we honor SKIP_CI and friends only when the commit containing that value is the tip, whether it's CI or PR. If you merge using GitHub's PR experience, for example, I don't think the SKIP_CI indicator gets included in the merge commit unless you included it in the PR message body.

**Comment by artemry-mlnx** [comment]
@vtbassmatt 
Are there any plans to add a possibility to skip PR triggering with `[skip ci]` comments?

**Comment by vtbassmatt** [comment]
I believe that should also work (as long as the `[skip ci]` is in the head commit of the push).

**Comment by ihnorton** [comment]
@vtbassmatt it does not work. See [this build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=2765&view=results), the head commit of which is https://github.com/TileDB-Inc/TileDB-Py/commit/68d937f31b761a2655e04142d503896a7c3e939d.

**Comment by vtbassmatt** [comment]
Hmm, that sounds like a bug in the service then. Could you please file a report on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)?

I'm going to close this issue because the bug can't be in the agent. (The agent just runs what the service tells it to run.)

**Comment by ihnorton** [comment]
https://developercommunity.visualstudio.com/content/problem/714477/pr-commit-with-skip-ci-in-message-still-triggers-a.html

**Comment by vtbassmatt** [comment]
That issue has been routed to a developer to investigate. Thanks for your patience.

**Comment by Vic152** [comment]
Is this being fixed?

**Comment by alvindutt** [comment]
Hi All

Is this still an issue on PR triggers?

**Comment by PaulTaykalo** [comment]
This is not about commit-based, but rather PR based, still

```

# Variable that checks if the PR title contains '[skip ci]' or '[skip build]'
variables:
  - name: should_skip_ci
    value: |
      or(contains(variables['System.PullRequest.PullRequestTitle'], '[skip ci]'), contains(variables['System.PullRequest.PullRequestTitle'], '[skip build]'))

stages:

  # Stage for checking if CI should be skipped
  # Then we can skip the rest of the CI pipeline by adding dependsOn: check_skip_ci 
  - stage: check_skip_ci
    displayName: Check if CI should be skipped
    condition: not(variables['should_skip_ci'])
    jobs:
      - job: check_skip_ci
        displayName: Check if CI should be skipped
        steps:
          - script: echo "This is a dummy job to check if CI should be skipped. Since Azure doesnt allow empty stages without jobs"

  - stage: build
    dependsOn: check_skip_ci

  ## OR
  - stage: build
    condition: and(succeeded(), not(variables['should_skip_ci']))
               
```
