### ISSUE TITLE
Multi-repo checkout does not work well with custom paths

### ISSUE THREAD

**Issue by pjcollins** [microsoft/azure-pipelines-agent#2718]
## Agent Version and Platform
Agent version: '2.164.1' on macOS and Windows.

## Azure DevOps Type and Version
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3368518

## What's not working?
​I'm using the ​Multi repo checkout feature in a YAML pipeline with the following syntax:

```yaml
- checkout: foo
  clean: true  
  submodules: recursive  
  path: s/bar/external/foo
  persistCredentials: true
```

The post-job step which cleans up credentials in this repo is failing on both macOS and Windows. With diagnostic output enabled, you can see that the `targetPath` is incorrect. The clean up attempt tries to execute a git command in the default checkout location `s/foo` rather than the custom path I have specified `s/bar/external/foo`.

```
##[command]git config --unset-all http.https://github.com/org/foo.extraheader
##[debug]Starting process:
##[debug]  File name: '/usr/bin/git'
##[debug]  Arguments: 'config --unset-all http.https://github.com/org/foo.extraheader'
##[debug]  Working directory: '/Users/azdo/_work/5/s/foo'
...
##[debug]Exited process 26852 with exit code 2
##[debug]Finished process 26852 with exit code 2, and elapsed time 00:00:00.0027457.
```

This produces an error on Windows that causes the entire job to fail. On macOS this is only treated as a warning.

#### macOS:
```
##[warning]An unsuccessful attempt was made using git command line to remove "http.extraheader" from the git config. Attempting to modify the git config file directly to remove the credential.
```

#### Windows:
```
##[error]The directory name is invalid
##[debug]Processed: ##vso[task.logissue type=error;]The directory name is invalid
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.GitCliManager.ExecuteGitCommandAsync(AgentTaskPluginExecutionContext context, String repoRoot, String command, String options, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.GitCliManager.GitConfigUnset(AgentTaskPluginExecutionContext context, String repositoryPath, String configKey)
   at Agent.Plugins.Repository.GitSourceProvider.RemoveGitConfig(AgentTaskPluginExecutionContext executionContext, GitCliManager gitCommandManager, String targetPath, String configKey, String configValue)
   at Agent.Plugins.Repository.GitSourceProvider.PostJobCleanupAsync(AgentTaskPluginExecutionContext executionContext, RepositoryResource repository)
   at Agent.Plugins.Repository.CleanupTask.RunAsync(AgentTaskPluginExecutionContext executionContext, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
```

**Comment by jpricket** [comment]
@pjcollins Thanks for reporting the issue. We will try to get this resolved as soon as we can.

**Comment by ivan-sam** [comment]
I've got a pipeline (YAML with multiple checkout) failing since today. It might be related to the change.
What I've discovered so far: it looks like the directory **c:\agent_work\1\s** defined by predefined variables (https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml):
 - Build.Repository.LocalPath
 - Build.SourcesDirectory
 - System.DefaultWorkingDirectory
is not available (at least with deployment job) which gives an error: **##[error]Container path not found: 'C:\RubyAgent3\_work\42\s** for this trivial pipeline:

```
resources:
  repositories:
  - repository: infrastructure
    name: Infrastructure
    type: git

jobs:
- deployment: Test
  pool: 'Ruby Hosted Agents'
  environment: Test
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: infrastructure
          path: infrastructure
        - script: 'dir $(pipeline.workspace)'
```

**Comment by jpricket** [comment]
@ivan-sam Thanks for the repro. I was able to see the problem. I will try to see what's causing this and get a fix checked in. Thanks.

**Comment by jpricket** [comment]
@ivan-sam I haven't been able to determine yet when this problem was introduced. I tried this against several older agents back to to 2.163.0, but it still happens there. Do you know the version of the agent you had before this started happening?

BTW, the simple work around is to set the workingDirectory on the script task
```javascript
  - script: 'dir $(pipeline.workspace)'
    workingDirectory: $(pipeline.workspace)
```

**Comment by ivan-sam** [comment]
> Current agent version: '2.163.1'

Regarding workaround: actually I found the problem with a different task: AzureResourceGroupDeployment@2 was failing with error: **##[error]The directory name is invalid**
It doesn't provide any information even with diagnostics enabled. So I started investigating and put some simple scripts to print out some info.

**Comment by jpricket** [comment]
I wonder if the repro you gave above is actually a different bug than the one you are having with your own yaml. If you determine the why "the directory name is invalid" or just find out some additional info, please let us know.

**Comment by ivan-sam** [comment]
@jpricket I've extended the script in order to get more details and it looks like the issue is that the folder **Build.Repository.LocalPath** (e.g. c:\agent_work\1\s) is **moved** to a new name when you do checkout of some repo other than **self** to explicit path. Really moved itself, not just the content. Previously the content was moved, but directory `s` remained, so it worked. And this directory is used in many tasks and steps, so it's not working without it.

```
resources:
  repositories:
  - repository: infrastructure
    name: Infrastructure
    type: git

jobs:
- deployment: Test1
  pool: 'Windows Hosted Agents'
  environment: Test
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: infrastructure
          path: infrastructure
        - script: 'dir $(pipeline.workspace)' # !!!!!!! only this fails with ##[error]Container path not found: 'C:\WindowsAgent3_work\42\s
        - script: 'dir $(pipeline.workspace)' # this outputs directory list and directory s in not listed
          workingDirectory: $(pipeline.workspace)
          condition: always()
- deployment: Test2
  condition: always()
  pool: 'Windows Hosted Agents'
  environment: Test
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: infrastructure
        - script: 'dir $(pipeline.workspace)'
- deployment: Test3
  condition: always()
  pool: 'Windows Hosted Agents'
  environment: Test
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - script: 'dir $(pipeline.workspace)'
- deployment: Test4
  condition: always()
  pool: 'Windows Hosted Agents'
  environment: Test
  strategy:
    runOnce:
      deploy:
        steps:
        - script: 'dir $(pipeline.workspace)'
```

This is the output of the job Test1, please note that **subdirectory `s` is not there**
```
01/27/2020  09:18 PM    <DIR>          .
01/27/2020  09:18 PM    <DIR>          ..
01/27/2020  09:18 PM    <DIR>          a
01/27/2020  09:18 PM    <DIR>          b
01/27/2020  09:18 PM    <DIR>          infrastructure
01/27/2020  09:18 PM    <DIR>          TestResults
               0 File(s)              0 bytes
               6 Dir(s)  30,520,569,856 bytes free
```

All the other jobs passed and all listed subdirectory `s`

**Comment by jpricket** [comment]
@ivan-sam I have already investigated that set of changes. Reverting them doesn't seem to change the behavior that you are seeing. I.e. even when I go back to the 2.163.0 build of the agent, no 's' directory is created. So, I am not sure when this new behavior was introduced. 

For others that may have this same error, if you create an s folder in the workspace dir, you can work around the problem.
```
  # after checkout
  - script: 'mkdir s'
    workingDirectory: $(pipeline.workspace)
```

Also note that if there are multiple checkouts in the same job, the 's' directory is preserved.

**Comment by ivan-sam** [comment]
Ok, might be some other code causes the issue.
But from the pipeline above it's easy to see that:
1. The real issue is that system variables are pointing to a not existing directory
2. The issue only happens when you do checkout of a repository (other than self) to an explicit location

@jpricket  Should I create a separate issue?

**Comment by ivan-sam** [comment]
@jpricket got it, will do.

But could you please check one more thing against previous version of the agent (I've  just got an idea looking through the changes)?

> I have already investigated that set of changes. Reverting them doesn't seem to change the behavior that you are seeing. I.e. even when I go back to the 2.163.0 build of the agent, no 's' directory is created.

It might be that in the previous version the directory was renamed as well, so after checking out to a specific name the directory `s` was renamed as well, **but** all the environment variables were updated to point to a new location as well.

So, could you please try extended pipeline above with variables reporting on a previous version?
If that was broken I'll create a separate ticket.

Thank you!

**Comment by ivan-sam** [comment]
Another workaround is to explicitly use `s` as a checkout path (I didn't like hardcoding `s` that's why I used to checkout to explicit location):
```
variables:
  infrastructure-checkout-folder: 's' # https://github.com/microsoft/azure-pipelines-agent/issues/2718
steps:
  - checkout: infrastructure
    path: $(infrastructure-checkout-folder)
  - script: 'dir $(pipeline.workspace)'
  # do anything with $(pipeline.workspace)/$(infrastructure-checkout-folder)
```
