### ISSUE TITLE
How to skip certain steps based on Git Commit(s)

### ISSUE THREAD

**Issue by nreddipalle** [microsoft/azure-pipelines-agent#2719]
This is more of kind of a question if anyone implemented of similar kind. We are setting up CI pipeline in Azure DevOps.. which includes building both BE and FE and having separate tasks for running Unit Tests for BE and FE.. I would like to skip steps based on Git commit.. i.e., if FE changes then only build and test FE.. if only BE changes they only build and test BE.. Has anyone implemented of similar kind? Thanks in advance..

**Comment by vtbassmatt** [comment]
You could write a job which decides whether it wants to build backend, frontend, or both. Have that job emit an output variable, and then have two downstream jobs which check the value. I haven't tested this, but it would go something like:

```yaml
jobs:
- job: decide
  steps:
  - script: |
      # do some work to decide what to build
      if [ $frontend ] && [ $backend ]; then
        echo '##vso[task.setVariable variable=build;isOutput=true]both'
      elif [ $frontend ]; then
        echo '##vso[task.setVariable variable=build;isOutput=true]frontend'
      elif [ $backend ]; then
        echo '##vso[task.setVariable variable=build;isOutput=true]backend'
      fi
    name: decider

- job: frontend
  dependsOn: decide
  condition: |
    or(
      eq(dependencies.decide.outputs['decider.build'], 'both'),
      eq(dependencies.decide.outputs['decider.build'], 'frontend')
    )
  steps:
  - script: echo building frontend
  - script: echo testing frontend

- job: backend
  dependsOn: decide
  condition: |
    or(
      eq(dependencies.decide.outputs['decider.build'], 'both'),
      eq(dependencies.decide.outputs['decider.build'], 'backend')
    )
  steps:
  - script: echo building backend
  - script: echo testing backend

```
