### ISSUE TITLE
Accessing $[variables['Build.Repository.Name']] not working

### ISSUE THREAD

**Issue by SmUrF3R5** [microsoft/azure-pipelines-agent#2721]
Unable to access build variables with more than one "."

i have a build pipeline and am unable to access vars that have more than one period. in the example below I can see the vars
- SourceBranch
- DefinitionName

but RepositoryName is null

```
variables:
  SourceBranch: $[variables['Build.SourceBranch']]
  DefinitionName: $[variables['Build.DefinitionName']]
  repo:  $[variables['Build.Repository.Name']]
```

I know the value is not null because if i print out the vars using I can see it there
```
Get-ChildItem Env:
```

**Comment by jtpetty** [comment]
@SmUrF3R5 - The variable $(Build.Repository.Name) is not known at plan compile time, only at job execution time.

You should be able to use $(Build.Reposity.Name) in the body of your script.

**Comment by SmUrF3R5** [comment]
@jtpetty that var is the first one I tried. Maybe I should clarify that I am trying to use them in a windows machine file copy task as a display name and also as part of the folder target path

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/windows-machine-file-copy?view=azure-devops

**Comment by jtpetty** [comment]
@SmUrF3R5 Can you try using $(Build.Reposity.Name) as part of the input to the task rather than attempting to assign it in the variables block.

**Comment by SmUrF3R5** [comment]
@jtpetty thats the first thing I did I only started using variables to figure out what was going on. I am on vacation for a couple weeks so I can’t really show you the output.

When I used 
display: $(Build.Reposity.Name)

It would fail or display as a taw string depending on the quotes. I’ll get more detailed info when I return. Thanks for the replies!

**Comment by SmUrF3R5** [comment]
```yaml
pool:
  name: MyPool

trigger:  
  - develop  
steps:

- task: PowerShell@2
  displayName: dump environment vars
  inputs:  
    targetType: 'inline'
    script: |
      Get-ChildItem Env:  

- task: WindowsMachineFileCopy@2
  displayName: $(Build.Reposity.Name)
  inputs:
    SourcePath: '$(source_dir)'
    MachineNames: 'localhost.local'
    AdminUserName: '$(MachineCopyUserName)'
    AdminPassword: '$(MachineCopyPass)'
    TargetPath: '\\SERVER\Test\'    
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
```

![image](https://user-images.githubusercontent.com/25916918/73372939-3968d580-4275-11ea-955f-98563dfeca20.png)


Environment Vars
![image](https://user-images.githubusercontent.com/25916918/73373662-38847380-4276-11ea-9ff7-e90c476f0b7a.png)

**Comment by SmUrF3R5** [comment]
The reason i think there is an issue with vars that bo more than 2 levels deep is represented below. If i try and access any var that is only two levels deep it works. 

```yaml
pool:
  name: MyPool

trigger:  
  - develop  
steps:

- task: PowerShell@2
  displayName: dump environment vars
  inputs:  
    targetType: 'inline'
    script: |
      Get-ChildItem Env:  

- task: WindowsMachineFileCopy@2
  displayName: $(Build.SourceBranch)
  inputs:
    SourcePath: '$(source_dir)'
    MachineNames: 'localhost.local'
    AdminUserName: '$(MachineCopyUserName)'
    AdminPassword: '$(MachineCopyPass)'
    TargetPath: '\\SERVER\Test\'    
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
```

![image](https://user-images.githubusercontent.com/25916918/73390694-db97b600-4293-11ea-96fe-2e90e8b350a9.png)


![image](https://user-images.githubusercontent.com/25916918/73390642-c589f580-4293-11ea-830e-b7cc4b1b3e8d.png)
