### ISSUE TITLE
Allow parameter defaults to be calculated based on other parameters

### ISSUE THREAD

**Issue by jmezach** [microsoft/azure-pipelines-agent#2737]
It would be nice if YAML pipelines would allow the default for a parameter to be calculated based on the value of another parameter, possible with some kind of transformation. For example, we run our projects through [SonarQube[(https://www.sonarqube.org) so we include the necessary tasks for this in our YAML templates. These tasks require a project key by which the project is known in SonarQube. We use a convention for this key which is something like com.<company-name>.<repository-name> all in lower-case. Since my template already needs the repository name to do other things, it would be nice if I can base the project key on that as a default value, using something like this:

```yml
parameters:
- name:  repositoryName
  type: string
  default: ''
- name: sonarQubeProjectKey
  type: string
  default: com.<company-name>.to-lower(${{ parameters.repositoryName }})
```

Users of the template then don't need to specify the project key, unless it deviates from our convention for some reason. I don't think this is possible at the moment, but would be a nice addition in my opinion.

**Comment by jmezach** [comment]
I guess I could add a script task to the pipeline that does the concatenation and transformation (lowercasing in my case). That does feel a little bit wasteful though, especially for "simple" things like this, since it would require scheduling that task to run on an agent, etc.

**Comment by vtbassmatt** [comment]
I agree this would be handy in this circumstance. We don't have a context for parsing template expressions inside parameters (for instance, we wouldn't want to follow templates there). I think Tommy was proposing something like:

```yaml
parameters:
- name: repositoryName
  type: string

variables:
- name: sonarQubeProjectKey
  value: com.company.${{ parameters.repositoryName }}
```

The lack of a `toLower` function is a separate concern, and one I have on my quarterly roadmap to address. You'd wrap the `value` section in `$[ ]` in order to access it. (Intentionally not showing a full example here, as I know it will come back to haunt me when someone stumbles across it in the future and wants to know why it doesn't work :grin:)

**Comment by jmezach** [comment]
I see. But if I'm not mistaken, this would not allow the user of the template to override the sonarQubeProjectKey anymore since it is now a variable and not a parameter, correct? I can see cases where it would be useful to allow overriding the value if necessary.

**Comment by vtbassmatt** [comment]
Good point. You'd have to get slightly more complicated in that case:

```
parameters:
- name: repositoryName
  type: string
- name: sonarQubeNameOverride
  type: string
  default: ''

variables:
- name: sonarQubeProjectKey
  value: com.company.${{ coalesce(parameters.sonarQubeNameOverride, parameters.repositoryName) }}
```

**Comment by jmezach** [comment]
Hmm, yeah, I guess that works. Still feels a bit convoluted and it isn't very intuitive, but I can live with that. I would still need the to-lower though. I couldn't find an existing issue for that, or is that tracked on some internal list?

**Comment by vtbassmatt** [comment]
Tracked internally, since it's server-side code. Sorry about that!

**Comment by jbrezina** [comment]
Is there any progress on this? We want to have default value for publishing artifacts based on branch.
```yml
parameters:
- name: Publish
  type: boolean
  default: ${{ startsWith(variables['Build.SourceBranchName'], 'release/') }}
  displayName: Publish to nuget feed?
```
So the default value is `true` for release branches and `false` for other branches, but can be changed by a user for **any** branch.
There is currently no easy way to do this.
