### ISSUE TITLE
Suggestion: add a way to control capitalization of environment variables

### ISSUE THREAD

**Issue by Lectem** [microsoft/azure-pipelines-agent#2763]
## Agent Version and Platform

Microsoft Hosted
Agent version 2.164.6
Ubuntu 18.04

## What's not working?

It is not possible to preserve casing of a environment variable

## Suggestion

Add a new property to variables (for example `toUpper` ?) that by default has the current behaviour of converting the names of variables to uppercase (for retro-compatibility), but let the use choose to not have it happen.

This is necessary for a lot of tools that work with environment variables and are case sensitive.
One such tool is CMake, where you can define a `<packagename>_ROOT` variable to hint at the installation location. Most of the packages are not uppercase.

The suggestion of using the command line task such as seen in issue https://github.com/Microsoft/azure-pipelines-agent/issues/1645 is not practical when you have a lot of different jobs and want to apply the variable globally AND use it to configure other tasks as a template variable for example.

**Comment by vtbassmatt** [comment]
It's a misfeature that we conflated pipeline variables with environment variables so much 😦 If you want to set actual environment variables, in a YAML pipeline do this:

```yaml
steps:
- script: echo $MyAnyCaseVar
  env:
    MyAnyCaseVar: 'my value'
```

Setting `variables` in the pipeline is not supposed to be a 1:1 mapping to environment variables. (And with the benefit of 20/20 hindsight, we would do this very differently.)

**Comment by Lectem** [comment]
Then add a `env:` for jobs, repeating the variable for all steps is annoying...

**Comment by bradselw** [comment]
I have confirmed that this works for preserving both casing and `.` characters in an environment variable name. Also, the `env:` is [supported for all steps, including tasks](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#steps):
```yaml
steps:
- task: VSTest@2
  displayName: 'Run tests'
  inputs:
    testAssemblyVer2: '$(TestContainers)'
    searchFolder: '$(TestContainerDirectory)'
    testFiltercriteria: '$(TestCaseFilter)'
    runOnlyImpactedTests: false
    uiTests: true
    vsTestVersion: toolsInstaller
    runSettingsFile: '$(RunSettingsFilePath)'
    codeCoverageEnabled: false
    testRunTitle: '$(TestRunTitle)'
    diagnosticsEnabled: True
    rerunFailedTests: true
    rerunMaxAttempts: 1
  timeoutInMinutes: 720
  env:
    VisualStudio.InstallationUnderTest.Path: 'C:\VS'
```
