### ISSUE TITLE
Repository checkout to custom path brings built-in env vars to incorrect state

### ISSUE THREAD

**Issue by ivan-sam** [microsoft/azure-pipelines-agent#2799]
## Agent Version and Platform
Version of your agent? 2.164.8

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
Having a job in a YAML pipeline with single checkout of a non-default repository to a custom path causes errors in subsequent steps due to incorrect state of built-in environment variables. I've noticed the wrong behavior shortly after the change for #2718 was rolled out, so I think it can be related. Submitted my thoughts to that issue but was asked to submit a new ticket, so here it is.

Simple reproduction script:
```
resources:
  repositories:
  - repository: infrastructure
    name: Infrastructure
    type: git

jobs:
- deployment: Test
  pool: 'Windows Hosted Agents'
  environment: Test
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: infrastructure
          path: infrastructure
        - script: 'dir $(pipeline.workspace)'
```
Expected behavior:  pipeline works with no errors
Actual behavior: pipeline fails with an error **##[error]Container path not found: 'C:\WindowsAgent3_work\42\s**

In order to investigate the issue I created an extended version of pipeline:
```
resources:
  repositories:
  - repository: infrastructure
    name: Infrastructure
    type: git

jobs:
- deployment: Test1 # checkout non-default repo to custom path - an error
  pool: 'Windows Hosted Agents'
  environment: Test
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: infrastructure
          path: infrastructure
        - script: 'dir $(pipeline.workspace)'
        - script: 'dir $(pipeline.workspace)'
          workingDirectory: $(pipeline.workspace)
          condition: always()
        - script: |
            echo Build.Repository.LocalPath: $(Build.Repository.LocalPath)
            echo Build.SourcesDirectory: $(Build.SourcesDirectory)
            echo System.DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
            echo pipeline.workspace: $(pipeline.workspace)
          workingDirectory: $(pipeline.workspace)
          condition: always()
- deployment: Test2 # checkout non-default repo to default path - no issue
  condition: always()
  pool: 'Windows Hosted Agents'
  environment: Test
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: infrastructure
        - script: 'dir $(pipeline.workspace)'
        - script: |
            echo Build.Repository.LocalPath: $(Build.Repository.LocalPath)
            echo Build.SourcesDirectory: $(Build.SourcesDirectory)
            echo System.DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
            echo pipeline.workspace: $(pipeline.workspace)
- deployment: Test3 # checkout default repo (self) to default path - no issue
  condition: always()
  pool: 'Windows Hosted Agents'
  environment: Test
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - script: 'dir $(pipeline.workspace)'
        - script: |
            echo Build.Repository.LocalPath: $(Build.Repository.LocalPath)
            echo Build.SourcesDirectory: $(Build.SourcesDirectory)
            echo System.DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
            echo pipeline.workspace: $(pipeline.workspace)
- deployment: Test4 # logging environment variables with no checkout
  condition: always()
  pool: 'Windows Hosted Agents'
  environment: Test
  strategy:
    runOnce:
      deploy:
        steps:
        - script: 'dir $(pipeline.workspace)'
        - script: |
            echo Build.Repository.LocalPath: $(Build.Repository.LocalPath)
            echo Build.SourcesDirectory: $(Build.SourcesDirectory)
            echo System.DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
            echo pipeline.workspace: $(pipeline.workspace)
```

**Findings:** 
 - After **checkout** built-in environment variables `Build.Repository.LocalPath`, `Build.SourcesDirectory`, `System.DefaultWorkingDirectory` are pointing to a directory that does not exist.

Output of the job Test1 (step CmdLine2):
```
01/27/2020  09:18 PM    <DIR>          .
01/27/2020  09:18 PM    <DIR>          ..
01/27/2020  09:18 PM    <DIR>          a
01/27/2020  09:18 PM    <DIR>          b
01/27/2020  09:18 PM    <DIR>          infrastructure
01/27/2020  09:18 PM    <DIR>          TestResults
               0 File(s)              0 bytes
               6 Dir(s)  30,520,569,856 bytes free
```
Please note that **subdirectory `s` is not there** 

Output of the job Test1 (step Cmdline3):
```
Build.Repository.LocalPath: C:\WindowsAgent3\_work\48\s
Build.SourcesDirectory: C:\WindowsAgent3\_work\48\s
System.DefaultWorkingDirectory: C:\WindowsAgent3\_work\48\s
pipeline.workspace: C:\WindowsAgent3\_work\48
```
Please note, that three built-in variables are pointing to a subdirectory `s` which is no longer there

It looks like **only** the checkout to custom path scenario does **move** default repository subdirectory `s` to a custom name, but doesn't update environment variables on agent.
That causes various issues depending on a type of the step, because all the steps assuming directories referenced by built-in variables are in place.

**Comment by ivan-sam** [comment]
There's workaround that shows the problem's nature:

```
resources:
  repositories:
  - repository: infrastructure
    name: Infrastructure
    type: git

jobs:
- deployment: Test
  pool: 'Windows Hosted Agents'
  environment: Test
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: infrastructure
          path: infrastructure
          # work around (should happen automatically as part of checkout)
        - script: 'mkdir $(System.DefaultWorkingDirectory)'
          workingDirectory: $(pipeline.workspace)
        - script: 'dir $(pipeline.workspace)' # there's no issue any more
```
