### ISSUE TITLE
Problem on connecting to services

### ISSUE THREAD

**Issue by gpad** [microsoft/azure-pipelines-agent#2803]
## Agent Version and Platform
Version of your agent? 2.144.0/2.144.1/...

Agent name: 'Hosted Agent'
Agent machine name: 'fv-az712'
Current agent version: '2.164.8'
Current image version: '20200211.1'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.

## Azure DevOps Type and Version
dev.azure.com
https://dev.azure.com/manpremo

## What's not working?
Please include error messages and screenshots.

Starting since some days ago a working pipeline as stopped to work because. Inside my tasj I'm using a postgres service and now the service is not more resolved at network level.

I have create a simple pipeline where I try to connect to postgres and I get this error:

```
psql: could not translate host name "postgres" to address: Name or service not known
```

```
resources:
  containers:
  - container: postgres
    image: postgres:latest
  - container: u18
    image: ubuntu:18.04
    options: '-v /usr/bin/sudo:/usr/bin/sudo -v /usr/lib/sudo/libsudo_util.so.0:/usr/lib/sudo/libsudo_util.so.0 -v /usr/lib/sudo/sudoers.so:/usr/lib/sudo/sudoers.so -v /etc/sudoers:/etc/sudoers'

stages:
- stage: xxx
  jobs:
  - job: yyy
    container: u18
    services:
      postgres: postgres
    steps:
      - script: |
          sudo apt update
          sudo apt install -y postgresql-client
          psql --host=postgres --username=postgres --command="SELECT 1;"
```

## Agent and Worker's Diagnostic Logs
[logs_1209.zip](https://github.com/microsoft/azure-pipelines-agent/files/4219993/logs_1209.zip)

**Comment by gpad** [comment]
Hello, Can anybody help me here?

**Comment by jtpetty** [comment]
@gpad - I will dig in. Was this working previously? If you do not run the job on the host itself instead of in a container can you resolve the hostname 'postgres'?

**Comment by gpad** [comment]
It stopped working and it works like a charm for months. What do you mean
with “not run the job on the host itself”?

Il giorno mar 3 mar 2020 alle 21:04 Tommy Petty <notifications@github.com>
ha scritto:

**Comment by jtpetty** [comment]
@gpad - Sorry, I did not word that properly. What I was trying to ask is if the job runs on the host and not inside a container, are you able to resolve the hostname 'postgres'? I am not aware of any change in the agent itself around how containers are setup that would cause a change in behavior and am wondering if the change was in docker itself not making the host alias visible inside another container. Is this on a hosted or private agent?

**Comment by jtpetty** [comment]
@gpad - I was able to setup a repro. Let me dig in and find out what is going on.

**Comment by jtpetty** [comment]
Ok, I thought I had a repro, but I think I was doing something incorrectly. 

I have this pipeline and it works fine for me. (I had to use node:10.17 instead of ubunutu because I am on a Mac an needed an image with node pre-installed to work in the pipeline)

```
resources:
  containers:
  - container: u18
    image: node:10.17
  - container: nginx
    image: nginx:1.17.6-alpine
    ports:
    - 80

stages:
- stage: xxx
  jobs:
  - job: yyy
    container: u18
    services:
      mynginx: nginx
    steps:
      - script: |
          curl mynginx:80
```

**Comment by gpad** [comment]
Is it possible that it’s related to Postgres? I have attached an example in
the issue wher Postgres doesn’t work.

Can you substitute ngnix with Postgres and try to ping it just to see if it
resolve the name?

Il giorno mer 4 mar 2020 alle 22:11 Tommy Petty <notifications@github.com>
ha scritto:

**Comment by jtpetty** [comment]
Ok, I tried this:

```
resources:
  containers:
  - container: u18
    image: node:10.17
  - container: nginx
    image: nginx:1.17.6-alpine
    ports:
    - 80
  - container: postgres
    image: postgres:latest
    ports:
    - 5432

stages:
- stage: xxx
  jobs:
  - job: yyy
    container: u18
    services:
      mynginx2: nginx
      mypostgres: postgres
    steps:
      - script: |
          curl mynginx2:80
          ping -c 1 mynginx2
          ping -c 1 mypostgres
```

I got this result:
```
64 bytes from nginx_nginx1176alpine_b7b37e.vsts_network_a51b35fbbc9c4ffc96131039c7b1adef (172.31.0.3): icmp_seq=1 ttl=64 time=0.104 ms

--- mynginx2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.104/0.104/0.104/0.000 ms
ping: mypostgres: Temporary failure in name resolution
```

**Comment by gpad** [comment]
Ok so it doesn't work only with postgres ?!?!

Il giorno mer 4 mar 2020 alle ore 22:35 Tommy Petty
<notifications@github.com> ha scritto:

**Comment by rnphilp** [comment]
I get the same issue here. It doesn't seem to matter whether I try to connect from the host or from another container, the alias doesn't get recognised. I ended up having to specify the IP address directly, which used to show in the pipeline output, but that's not a good solution. 
@gpad - as a slight aside ours stopped working on a recent image update and we had to specify the postgres password as an environment variable the container: 
```
  - container: postgres
     image: postgres:latest
     ports:
     - 5432:5432
     env:
         POSTGRES_PASSWORD: 'postgres'
```
as per https://hub.docker.com/_/postgres

@jtpetty - any ideas why the alias doesn't work for the Postgres container?

**Comment by jtpetty** [comment]
@rnphilp - in my local dev environment, I had docker dump out all the info about the container and I can see the network alias is set properly (according to docker), so I do not think this is a bug with the agent. It is possible this is a bug with docker, but that would not explain why it works for nginx but not Postgres in the same pipeline. 

Is it possible for you to use an older tag of the Postgres container (something not 'latest') that would point to a previously working version? That would tell us if the issue is related to something specific to the Postgres container.

**Comment by rnphilp** [comment]
Ours points at `postgres:11`. However, I've tried going back to the 11.5 release. The ip now displays in `initialize containers` again, under the command:
`/usr/bin/docker port e477790f988520840af51be6841ce6a7e3d3239713ebc187d3562ec3177f5038
`
Unlike the latest build of 11. However, the alias still isn't recognised. 
Also tried `postgres:10.0` but get similar results.

**Comment by gpad** [comment]
I also have tried with an old tag and it doesn’t work.

I have used this configuration since last September and it works until 1
month ago.

It starts to don’t work without any apparent reason I think that it’s
related to something changed inside the azure platform because nothing else
changed.

Il giorno ven 6 mar 2020 alle 18:12 Rob Philp <notifications@github.com> ha
scritto:

**Comment by Dunstark** [comment]
I'm running a docker-compose inside a pipeline with a postgres image and have been suffering from a similar issue. Switching from `postgres:11.7-alpine` to `postgres:11.5-alpine` appears to have solved the issue, at least temporarily.

**Comment by Sythanis** [comment]
I was facing the same issues. For me using the `bitami/postgesql` image worked, but only if I started it from a bash step wait a couple of seconds and do the rest of work. I am using something like this as a workaround

```
steps:
          - bash: | 
              docker stop test-db
              docker rm test-db
              docker run --name test-db -p 5432:5432 -d -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=some_db bitnami/postgresql@sha256:d9a5484c3fecd47525bd1a0775327497090295f5a31bc27b7066fac3b9cb8729
              sleep 10
       - bash: |
           tests that need the postgres db
       - bash: |
           docker stop test-db
           docker rm test-db
```

Not really a solution, but a workaround

**Comment by jtpetty** [comment]
@mjroghelia - Assigning to you for awareness. I think we have come to the conclusion that the issue lies with the Postgres container itself, but I think we should leave this issue open a little longer to collect more information.

**Comment by ntziolis** [comment]
Wanted to let people that find this know that this seems to work now. Hostname was properly assigned to a postgis container (postgres+spacial types), however we ran into a dependency issue #3130

**Comment by s4ke** [comment]
I ran into the issue as well. I was able to fix it by using this:

```
  - container: pg12
    image: postgres:12-alpine
    env:
      POSTGRES_DB: "xxxx"
      POSTGRES_USER: xxxx"
      POSTGRES_PASSWORD: "xxxxx"
      PGDATA: "/data/postgres"
    options: --name pg12
```
