### ISSUE TITLE
PowerShell 7 errors are not written to the console

### ISSUE THREAD

**Issue by hbuckle** [microsoft/azure-pipelines-agent#2853]
## Agent Version and Platform
Current agent version: '2.165.0'
Current image version: '20200308.0'

Windows

## Azure DevOps Type and Version
dev.azure.com

## What's not working?

The hosted agents have recently updated to PowerShell 7. Since this change errors are not being written to the console. This seems to be related to the new `ConciseView` error setting. After changing it to `NormalView` errors are displayed again

azure-pipelines.yaml
```yaml
jobs:
  - job: job1
    pool:
      vmImage: windows-latest
    steps:
      - pwsh: |
          throw "test"
        failOnStderr: true
        errorActionPreference: stop
        condition: always()
        displayName: ConciseView
      - pwsh: |
          $ErrorView = "NormalView"
          throw "test"
        failOnStderr: true
        errorActionPreference: stop
        condition: always()
        displayName: NormalView
      - powershell: |
          throw "test"
        failOnStderr: true
        errorActionPreference: stop
        condition: always()
        displayName: PowerShell 5
```

![image](https://user-images.githubusercontent.com/18499079/76539075-2e11e800-6478-11ea-9629-c8484346ddf6.png)

![image](https://user-images.githubusercontent.com/18499079/76539107-3833e680-6478-11ea-83ce-f661a36fe84a.png)

![image](https://user-images.githubusercontent.com/18499079/76539137-4124b800-6478-11ea-9abf-b0df8a35ab22.png)
