### ISSUE TITLE
Feature request: Add "Pull Request Merge Target" as version option in Download Pipeline Artifact

### ISSUE THREAD

**Issue by ian-craig** [microsoft/azure-pipelines-agent#2885]
## Summary

Add an option to the "Build version to download" dropdown called "Pull Request Merge Target". When this is selected, the task searches builds for the specified pipeline on the PR target branch to find the latest one which was run on the merge-base for this PR.

## Use case

There are lots of tools which diff build stats, snapshots, generated code, etc. to give a summary of what the impact of a code change is. (e.g. [webpack-stats-diff](https://github.com/ZachGawlik/webpack-stats-diff))

It's often not practical to check in these files, as they may be changed by every commit, would conflict a lot, and are more reliable when done by a clean CI build. So, it would be useful if there was an easy way to publish and download these as artifacts. For this to work, there needs to be a way to guarantee that the artifact downloaded matches the source code baseline.

## Implementation

What I would expect the PR pipeline's YAML to contain:
```yaml
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'e33c77e0-9a60-411c-a0ce-14232f443934'
    definition: '1234'
    buildVersionToDownload: 'pullrequestMergeTarget'
```

What I think the task would need to do (in src\Agent.Plugins\PipelineArtifact\PipelineArtifactPluginV2.cs)
1. Check this build was triggered by a PR, grab the TargetBranch and PullRequestId from env.
2. Query the Git PullRequest API for PullRequestId, grab the LastMergeTargetCommit
3. Query the Builds API for builds on TargetBranch after LastMergeTargetCommit.Push.Date
4. Get the first build where Build.Source == LastMergeTargetCommit.CommitId
...and then once you have the BuildId the rest is the same as the 'specific' config.

I am willing to contribute this implementation, and open to suggestions on how to improve it.

@fadnavistanmay
