### ISSUE TITLE
Agent.TempDirectory ambiguity with container builds

### ISSUE THREAD

**Issue by sgerace** [microsoft/azure-pipelines-agent#2937]
I have a question related to the behavior of the `Agent.TempDirectory` [predefined variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables). I'm running container-based builds on a hosted agent and I have my working directory set to `/mnt/work`. Inside this folder, there is the expected `_temp` directory which should represent the path to the agent temporary directory _on the host_. That said, when I log the value for `$(Agent.TempDirectory)`, it is actually set to `/__w/_temp`, which is the directory _in the container_ to which the host temporary directory is mapped. This makes total sense for `$(Agent.TempDirectory)` to have this value when working with containers, since within the pipeline, chances are you are working in the containers themselves. However, I have several steps that are not container builds (performing miscellaneous tasks that don't require OS/host isolation). Furthermore, in the `resources` section of the yaml, something like the following leads to unexpected behavior:
```
resources:
  containers:
  - container: mysql
    image: mysql:5.7
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - $(Agent.TempDirectory)/mysql:/var/lib/mysql:delegated
```
In this case, it seems most logical for `$(Agent.TempDirectory)` to refer to `/mnt/work/_temp` and not `/__w/_temp` since we are clearly referring to a path on the host machine. I understand that there is going to be significant complexity identifying the _correct_ value to use in each case, so at this point I'm just wondering if there is another variable that I can use to get the location of the temporary directory within the _host filesystem_.
