### ISSUE TITLE
No agent found in pool which satisfies the following demand

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-agent#2996]
## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.165.0 
Windows 2012 R2

## Azure DevOps Type and Version
dev.azure.com

https://dev.azure.com/{organization} or https://buhlergroup.visualstudio.com

## What's not working?
We are unable to run a pipeline on a specified agent. The pipeline fails with:
> ##[error]No agent found in pool BUZ-MYB which satisfies the following demand: agent.name. All demands: agent.name -equals 'ecom-app02-test', Agent.Version -gtVersion 2.163.1
Pool: BUZ-MYB

However the agent is there and available:
![image](https://user-images.githubusercontent.com/498834/83494061-fedaa800-a4b5-11ea-9c9f-f6c33f2a326d.png)
![image](https://user-images.githubusercontent.com/498834/83494007-eb2f4180-a4b5-11ea-9b2e-c165f10e150a.png)

But the agent is blissfully oblivious of any jobs:
![image](https://user-images.githubusercontent.com/498834/83494135-19148600-a4b6-11ea-86cd-1ec18f394049.png)

Running `run.sh` manually does not help.
Restarting the agent does not help.
In the past, restarting the agent seemed to help but no longer.
This YAML has run successfully in the past.

## Agent and Worker's Diagnostic Logs
There are no errors in `Agent_20200602-074135-utc.log` and no worker log is generated.

**Comment by cawoodm** [comment]
Switching to a matrix strategy and everything works fine:
## Old YAML
```
- stage: deploy_stage_1

  jobs:
  - job: deploy_job_1

    pool:
      name: BUZ-MYB
      demands:
        - agent.name -equals 'ecom-app02-test'
```

## New YAML
```
- stage: deploy_stage_1

  jobs:
  - job: deploy_job_1

    strategy:
      matrix:
        ecom_app02_test:
          AGENT_NAME: 'ecom-app02-test'

    pool:
      name: BUZ-MYB
      demands:
        - agent.name -equals $(AGENT_NAME)
```
