### ISSUE TITLE
Environment variables from Library are being cast to uppercase

### ISSUE THREAD

**Issue by wayoflife** [microsoft/azure-pipelines-agent#3082]
Reopening this Issue since it is not being adressed

See  #1981 #1645 microsoft/azure-pipelines-tasks#9687  (and probably more)

Variable names entered in the Library and imported to Pipelines via Groups are not preserved.

**This leads to serious issues with other systems that require those Variables Names in a case sensitive manner.**

Additionally this behaviour is not documented:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

And goes strictly against what you would expect by looking at the naming convetions of predefined variables:
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

This behaviours needs to be changed so that variable names are propagated to agents "as is" without any changes

**Comment by aberrios85** [comment]
It looks to be documented here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#environment-variables

However I agree that variables should be passed, untouched, to the agent. It's very annoying when the task being run takes an environment variable that's mixed case and does not pick it up because the defined variable has been converted to upper.

**Comment by akamud** [comment]
We are having the same problem due to the case transformation. I don't see any workaround at the moment, since we are integrating with a system that treats all env variables as case-sensitive. We can't change this, so we should be able to somehow set *environment variables* (not command line arguments) in the original case we intended.

**Comment by mjroghelia** [comment]
As mentioned above, this behavior is documented, and it is not going to be changed, as doing so would break backward compatibility.

However, note that it is possible to declare environment variables on the step level within a job and case is preserved, so you can explicitly map a pipeline variable to the expected environment variable without losing the case, you just can't rely on the automatic mapping to produce the result you want.

In the following example I have a variable named "myVar". For each of the three examples I set the environment variable "myEnvVar" using the value of `myVar`. This would work the same whether `myVar` was defined in the YAML or loaded from a variable group. If you run this example you will see cmd and Powershell report the environment variable in its original casing. The Python example does not, because Python itself works on the assumption environment variables are case insensitive and normalizes them as uppercase. 

```yaml
trigger: none

pool:
  vmImage: windows-latest

variables:
  myVar: VarValue

stages:
- stage: stage1
  jobs:
  - job: printEnv
    steps:
    # cmd
    - script: set
      env:
        myEnvVar: $(myVar)
    # powershell
    - task: PowerShell@2
      env:
        myEnvVar: $(myVar)
      inputs:
        targetType: 'inline'
        script: |
            gci env:* | echo
    # python
    - task: PythonScript@0
      env:
        myEnvVar: $(myVar)
      inputs:
        scriptSource: 'inline'
        script: |
            import os
            for k,v in os.environ.items():
              print(k + ' = ' + v)
```
