### ISSUE TITLE
Env Doesn't Override Pipeline Variables

### ISSUE THREAD

**Issue by jabberwik** [microsoft/azure-pipelines-agent#3091]
## Agent Version and Platform
Version of your agent? 2.173.0
OS of the machine running the agent? Hosted Ubuntu16

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
For the following pipeline:
```yaml
variables:
  foo: bar

steps:
- script: echo $FOO
- script: echo $FOO
  env:
    FOO: baz
```

I expect to see `bar` then `baz`, but I actually see `bar` twice. How can I "overwrite" a variable for a particular step?
