### ISSUE TITLE
Hosted agents using 2.175.1 fail with Node error when using Containers and Azure KeyVault task

### ISSUE THREAD

**Issue by mihsoft** [microsoft/azure-pipelines-agent#3121]
Agent Version and Platform
v2.175.1 - Hosted

OS of the machine running the agent? OSX/Windows/Linux/...
Linux

Azure DevOps Type and Version
Azure DevOps

What's not working?
When using a hosted agent - v2.175.1 and trying to run a pipeline with a custom container image and the Azure KeyVault task with Node 10 installed we receive the following error:

Sample pipeline:

```
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      KeyVaultName: my-vault
      SecretsFilter: '*'
      RunAsPreJob: false
```
**##[error]This step requires a node version that does not exist in the agent filesystem. Path: /usr/bin/node**

Manually setting the Agent back to 2.174.3 resolved the issue.
