### ISSUE TITLE
Feature request: Ability to specify depended containers

### ISSUE THREAD

**Issue by ntziolis** [microsoft/azure-pipelines-agent#3130]
Version of your agent: 2.175.2

Agent name: 'Hosted Agent'
Agent machine name: 'fv-az89'
Current agent version: 2.175.2
Current image version: '20200920.1'
Agent running as: 'vsts'

## What's not working?
When having 2 containers with one depending on the other there is no way to specify the order in which they start which causes the container with dependencies to fail.

Concrete example:
```yml
resources: 
  containers:
    - container: database
      image: postgis/postgis:12-3.0-alpine
      options: --expose 5432
      env:
        POSTGRES_PASSWORD: somepw
    - container: hasura
      image: hasura/graphql-engine:v1.3.2
      options: --expose 8080
      env: 
        HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:somepw@database:5432/postgres
        HASURA_GRAPHQL_ADMIN_SECRET: mysecret
```
This resulted in the following:
- The hasura container was started first (despite being second in the containers array
- The hasura image runs a command on startup that checks if it can find the `HASURA_GRAPHQL_DATABASE_URL`
- Since the database container was not yet available the host name resolution fails
- Which in turn causes the hasura image to exit

Note:
- The hasura image does have retry logic build in for inital connection with the database
- But **ONLY** when the hostname can be resolved, otherwise it simply exits

Workaround:
- We provided the `--restart always` as part of hasura container options

While not perfect it did work in this specific scenario but only because the hasura container exited when the hostname was not resolved. This wont be the case for all container images hence the need to be able to specify dependencies.
