### ISSUE TITLE
Error building WinForms application on hosted agent version 2.177.1

### ISSUE THREAD

**Issue by DonKarlssonSan** [microsoft/azure-pipelines-agent#3172]
## Agent Version and Platform
v2.177.1
Image: Windows
Azure hosted agent
````
Agent name: 'Hosted Agent'
Agent machine name: 'WIN-K81SKPHT5FM'
Current image version: '20201116.1'
Current agent version: '2.177.1' 
````
## Azure DevOps Type and Version
https://dev.azure.com/kommuninvest

## What's not working?
Since the release of v2.177.1, our WinForms application does not build in Azure DevOps.
The solution builds fine on two developer machines
When trying the exact same source code that was used in the last successful build, it also fails.
The build step:
````
    - task: VSBuild@1
      displayName: 'Build solution MySolution.sln'
      inputs:
        solution: 'MySolution.sln'
        platform: 'any cpu'
        configuration: 'release'
````

The compilator error:
````
"D:\a\1\s\MySolution.sln" (default target) (1) ->
"D:\a\1\s\MyProject.Tests\MyProject.Tests.csproj" (default target) (15) ->
(CoreCompile target) -> 
  D:\a\1\s\MyProject.Tests\MyTests.cs(2,7): error CS0246: The type or namespace name 'AAA' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\MyProject.Tests\MyProject.Tests.csproj]
  D:\a\1\s\MyProject.Tests\MyTests.cs(3,7): error CS0246: The type or namespace name 'BBB' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\MyProject.Tests\MyProject.Tests.csproj]

    5198 Warning(s)
    2 Error(s)

Time Elapsed 00:01:39.68
##[error]Process 'msbuild.exe' exited with code '1'.
```` 

## Agent and Worker's Diagnostic Logs
Rather not in public

Setup that works:
```` 
Current agent version: '2.175.2' 
Current image version: '20201108.1'
```` 

Please tell me if you need more info.
