### ISSUE TITLE
Custom tasks and node versions

### ISSUE THREAD

**Issue by rossbeehler** [microsoft/azure-pipelines-agent#3195]
I'm trying to run a custom task on node 12 or newer.  The azure-pipelines-task-lib repo claims that node14 is supported: https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/nodeEnvironment.md.  However, in my usage of the self-hosted agent in docker (as explained in https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops), only node versions 6 and 10 are available if you look in the underlying setup in /azp/agent/externals.  I checked this is true for all flavors of the self-hosted agent.

I thought the way to pull this off was to use the "Node.js Tool Installer task" (NodeTool@0), but this does not seem to have an effect on the execution of my custom task.  I see it installing a newer version to, for example, /azp/agent/_work/_tool/node/12.20.0/x64/bin, but when the custom task runs, it always uses the node versions packaged with the agent.

Here's the relevant piece of my task.json

```
    "execution": {
        "Node10": {
            "target": "main.js"
        }
    }
```

And my pipelines.yml related to this task (custom task info obscured):

```
          - task: NodeTool@0
            displayName: Use Node 12.x
            inputs:
              versionSpec: 12.x
              checkLatest: true

          - task: MyCustomTask@1
            inputs:
              input1: value1
```

And output in my custom task saying it's using node10:

```
Starting: MyCustomTask
==============================================================================
Task         : My Custom Task
Description  : My Custom Task
Version      : 1.0.0
Author       : Author1
Help         : https://dev.azure.com/MyOrg/MyProject/_git/my-custom-task
==============================================================================
##[debug]Using node path: /azp/agent/externals/node10/bin/node
```

Am I missing something, or is this simply not supported until the agents ship with specifically something like node14?
