### ISSUE TITLE
Clean option not honored in build pipeline

### ISSUE THREAD

**Issue by luckerby** [microsoft/azure-pipelines-agent#3342]
I'm using a YAML pipeline to do a simple MSBuild step. The source git repository is hosted on Azure DevOps. The pool has one single self-hosted agent so far, as I'm performing various tests. The YAML file is below:

```
name: $(Build.BuildId)
pool: $(var.poolName)

trigger:
  batch: true
  branches:
    include:
    - develop

resources:
  - repo: self

stages:
- stage: Build
  displayName: First stage
  jobs:  
  - job: Build
    displayName: Build Code
    steps:
    - task: MSBuild@1
      inputs:
        solution: '$(var.target)'
        msbuildVersion: '16.0'
        msbuildArguments: '/target:ReleaseX64'
        msbuildArchitecture: 'x64'
```

In the classic UI interface, the "clean" option for the step that gets the sources is set to `false`. This is seen below:

![image](https://user-images.githubusercontent.com/31319583/112051480-a6ff5180-8b5a-11eb-902c-099bcebd6e95.png)

Running this pipeline however doesn't result in the expected behavior: every single run the folder where the git repository is checked out to gets cleaned up first. Setting `System.Debug` to `true`, and looking at the logs captured for the checkout step, I spot:
```
##[debug]clean=True
```

Further down, I see:
```
git clean -ffdx
```

So based on the outcome, it's as if the agent is explicitly instructed to clean the git folder. This also matches what the documentation states [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#azure-pipelines-azure-devops-server-2019-and-newer) when the option to clean is indeed set. It's only that in my case this is specifically not turned on.

The workaround I've found is to specifically enter a `checkout` step within the YAML file itself, as follows:
```
    - checkout: self
      clean: false
```

This results in the git folder to be kept between successive runs, as opposed to being emptied every single time. Yet having to perform this workaround doesn't seem to be in sync in what the documentation says, or there's currently a bug that needs to be fixed within the agent code.

Azure DevOps self-hosted agent, version `2.183.1` running on Windows Server 2019.
