### ISSUE TITLE
configure scaleset agent pool with arm template

### ISSUE THREAD

**Issue by jchauncey** [microsoft/azure-pipelines-agent#3358]
I am wanting to create a scale set that utilizes our custom image and also has the necessary azsecpack extensions installed. It would be awesome if I could also preconfigure the scale set to create and join a pool. When I examine the configuration of the extension on an existing pool I see the following: 

note this is a bicep file

```yaml
name: 'Microsoft.Azure.DevOps.Pipelines.Agent'
properties: {
  publisher: 'Microsoft.VisualStudio.Services'
  type: 'TeamServicesAgentLinux'
  typeHandlerVersion: '1.21'
  autoUpgradeMinorVersion: true
  settings: {
    isPipelinesAgent: true
    agentFolder: '/agent'
    agentDownloadUrl: 'https://vstsagentpackage.azureedge.net/agent/2.184.2/vsts-agent-linux-x64-2.184.2.tar.gz'
    enableScriptDownloadUrl: 'https://vstsagenttools.blob.core.windows.net/tools/ElasticPools/Linux/6/enableagent.sh'
  }
}
```

Can I use the settings from the deployment group extension to wire up the pool?

```json
"settings": {
  "VSTSAccountName": "[parameters('VSTSAccountName')]",
  "TeamProject": "[parameters('TeamProject')]",
  "DeploymentGroup": "[parameters('DeploymentGroup')]",
  "AgentName": "[parameters('AgentName')]",
  "Tags": "[parameters('Tags')]"
},
"protectedSettings": {
   "PATToken": "[parameters('PATToken')]"
}
```
