### ISSUE TITLE
Can't download pipeline artifact files use matching patterns starting with artifact name

### ISSUE THREAD

**Issue by beatcracker** [microsoft/azure-pipelines-agent#3416]
I'm raising this issue here since pipeline artifacts publish/download tasks are agent plugins.

## Agent Version and Platform

Agent `2.186.1` on `ubuntu-20.04`

## Azure DevOps Type and Version

dev.azure.com

## What's not working?

Pipeline artifact download task with file matching patterns patterns doesn't work as expected.  When downloading multiple artifacts, you can't filter files by artifact name.

According to [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts#multiple-artifacts):

> File matching patterns should assume the first segment of the pattern is (or matches) an artifact name. For example, `WebApp/**` matches all files from the `WebApp` artifact. The pattern `*/*.dll` matches all files with a `.dll` extension at the root of each artifact.

So one might expect that for existing artifact `WebApp`, the pattern `WebApp/**` will download all files. Unfortunately this doesn't happen and such patterns result in 0 files being downloaded.

Related Stack Overflow question: https://stackoverflow.com/questions/67567408

### Example

This template will not download any files in the `Download` job.

```none
Minimatch patterns: [test/*.xyz]
Filtered 0 files from the Minimatch filters supplied.

```

```yaml
pool:
  vmImage: ubuntu-latest

jobs:
  - job: Publish
    steps:
      - bash:
          mkdir -p test
          touch test/test.xyz
        displayName: Create artifact

      - bash: find . -name '*.xyz'
        displayName: List created artifact

      - publish: test
        artifact: test
        displayName: Publish test

  - job: Download
    dependsOn: Publish
    steps:
      - download: current
        patterns: test/*.xyz
        displayName: Download using pattern

      - bash: find $(Pipeline.Workspace) -name '*.xyz' 
        displayName: List downloaded artifacts
```
