### ISSUE TITLE
DownloadPipelineArtifact: Support in-progress builds

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/azure-pipelines-agent#3511]
## Agent Version and Platform
Version of your agent? 2.190.0

OS of the machine running the agent? Windows Server 2019

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/microsoft

## What's not working?
We have the following pipeline setup:
![multi-stage pipeline](https://user-images.githubusercontent.com/2766036/130502298-b29e0a43-b432-4d37-8dd9-a6d979dbce97.png)

What we would like to do is be able to download PPE artifacts from another pipeline even if "Deploy Prod" is still "in-progress" waiting for the checks to succeed (or fail). We know this is safe because we add tags on successful deployments which the dependent pipeline looks for:
```yaml
- task: DownloadPipelineArtifact@2
  displayName: Download artifacts
  inputs:
    source: specific
    project: redacted
    pipeline: redacted
    runVersion: latest
    allowCanceledBuilds: true # So that we can get PPE artifacts after we cancel deployments to Prod
    tags: ${{ lower(parameters.environment) }} # <-- This
    artifact: Redacted-${{ parameters.environment }}
```

The specific feature request is to add another input, `allowInProgressBuilds`, that will allow downloading from in-progress builds. I'd be fine making `tags` required if that option was enabled, because that's how we determine whether we can download from a build or not.
