### ISSUE TITLE
Environment agent seems to be stuck in a running state

### ISSUE THREAD

**Issue by strtdusty** [microsoft/azure-pipelines-agent#3579]
## Agent Version and Platform
Version of your agent? 2.144.0/2.144.1/...
2.193.1

OS of the machine running the agent? OSX/Windows/Linux/...
Windows Server 2016 Datacenter

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/Itron
Itron

## What's not working?
Environment agents seem to be stuck in a running state.  However, the agent is not doing anything and appears to be done.  Subsequent jobs/deployments in the pipeline end up stuck in a queued state.  This happens on different agents, but seems to happen every time we run.
The environment shows that an agent is still running:
![image](https://user-images.githubusercontent.com/1013039/138743238-5be2ab29-5b9a-4da4-8e05-91965f6e4ace.png)
The pipeline thinks it is done but is waiting to start the next phase (queued)
![image](https://user-images.githubusercontent.com/1013039/138743592-57069152-fbc6-4411-8929-76285f6c6664.png)

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here
[Worker_20211025-163049-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7412734/Worker_20211025-163049-utc.log)
[Agent_20211022-231144-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7412735/Agent_20211022-231144-utc.log)
.

**Comment by tinylabspace** [comment]
Take a look at this doc, I ran into something similar recently where a YAML job named "deploy" caused an environment job to hang in a pending state indefinitely. Your worker log has a number of steps with "deployment" in the name, _Processing step: DisplayName='Backup Directory before Deployment'_.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops

At the top:

_Important

Job and stage names cannot contain keywords (example: deployment)._

**Comment by strtdusty** [comment]
@tinylabspace I had seen that but the docs didn't mention that tasks (just jobs/stages) couldn't have a displayName with Deployment in them.  Also, though it is a bit ambiguous, I believe the docs are saying that the actual name of the job/stage can't have deployment, but the displayName is not mentioned.  We have managed to work around this issue by reducing the number of total steps in the stages.  A few of our templates are called repeatedly with control parameters indicating which parts of the template should be run.  We moved that logic from "conditions" to template syntax so the step isn't even compiled in if it is not used.  That has allowed us to proceed without any more hangups.  Support has indicated there are limits on the number of steps and that there are backlog items to resolve issues like ours, but they have not definitively correlated our issue to the backlog items.

**Comment by anatolybolshakov** [comment]
Hi @strtdusty do you still see this issue with the latest agent version? There have been some fixes related to race conditions for job execution some time ago.

**Comment by strtdusty** [comment]
@anatolybolshakov  I will upgrade and do some testing

**Comment by alexander-smolyakov** [comment]
@strtdusty do you have any updates?

**Comment by strtdusty** [comment]
We still see the same behavior with the deployment stuck running forever
after upgrading to the latest agent version.

**Comment by ismayilov-ismayil** [comment]
Hi @strtdusty, sorry for late response. I am trying to reproduce your issue. Meanwhile do you have a chance to check same pipeline with Microsoft hosted agent

**Comment by strtdusty** [comment]
Unfortunately, we need private vnet access so it cannot be a hosted agent.

**Comment by ismayilov-ismayil** [comment]
@strtdusty could you share your pipeline yaml file? 
Please, remove passwords, tokens and any confidential data from files

**Comment by ceilingfish** [comment]
Reproduced with the following pipeline:

```yaml
parameters:
  - name: environmentName
    displayName: Environment Name
    type: string

trigger: none
      
stages:
  - stage: Deploy
    displayName: Deploy to ${{ parameters.environmentName }}
    jobs:
      - deployment: Deploy
        environment:
          name: $(EnvironmentName)
          resourceName: host
          resourceType: VirtualMachine
          tags: windows
        strategy:
          runOnce:
            deploy:
              steps:
                - pwsh: Write-Host "hello"
```

hangs indefinitely. However the following executes just fine:

```yaml
parameters:
  - name: environmentName
    displayName: Environment Name
    type: string

trigger: none
      
stages:
  - stage: Install
    displayName: Install on ${{ parameters.environmentName }}
    jobs:
      - deployment: Install
        environment:
          name: $(EnvironmentName)
          resourceName: host
          resourceType: VirtualMachine
          tags: windows
        strategy:
          runOnce:
            deploy:
              steps:
                - pwsh: Write-Host "hello"
```
