### ISSUE TITLE
Multi-checkout with a path in a container fails

### ISSUE THREAD

**Issue by lanphiergm** [microsoft/azure-pipelines-agent#3617]
## Agent Version and Platform
Version of your agent? 2.181.2
OS of the machine running the agent? Windows 10 21H1

## Azure DevOps Type and Version
on-premises Azure DevOps Server 2020.1.1 Patch 1

## What's not working?
If a YAML pipeline is checking out more than one repository, provides custom paths for these checkouts, and is performing the job inside a container, the agent fails to perform the checkout with this error:

```
##[error]Unable to process command '##vso[plugininternal.updaterepositorypath alias=self;]C:\azagent\[agentname]\_work\3\s' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Repository path 'C:\azagent\[agentname]\_work\3\s' should be located under agent's work directory 'C:\__w\3'.
```

It appears that the test to check if the path is under the agent working directory is failing because it is trying to compare the path to the repo in the agent context to the path to the repo in the container context.

## Steps to Reproduce
1. Create two git repos with `README.md` files in each.
2. Create a pipeline in one of the repos with this YAML:
```
resources:
  repositories:
    - repository: MultiCheckoutResource
      name: MultiCheckoutResource
      ref: refs/heads/main
      type: git

pool:
  name: SandboxPool
  demands:
    - docker

# Commenting out this line works as expected
container: mcr.microsoft.com/windows/nanoserver:20H2

steps:
- checkout: self
  path: s
- checkout: MultiCheckoutResource
  path: s/resource

- script: |
    echo Main:
    type $(System.DefaultWorkingDirectory)\README.md
    echo.
    echo.
    echo Resource:
    type $(System.DefaultWorkingDirectory)\resource\README.md
  displayName: 'Show READMEs'
```
3. Save and run the pipeline
4. Note that the build fails with the specified error

## Agent and Worker's Diagnostic Logs
[Agent.log](https://github.com/microsoft/azure-pipelines-agent/files/7564764/Agent.log)
[Worker.log](https://github.com/microsoft/azure-pipelines-agent/files/7564766/Worker.log)
