### ISSUE TITLE
DECODE_PERCENTS is not working on Azure devops agent

### ISSUE THREAD

**Issue by mrlioncub** [microsoft/azure-pipelines-agent#3672]
Issue: https://github.com/microsoft/azure-pipelines-agent/issues/3270

Reproduced on the agent version: '2.195.2'

**Comment by max-zaytsev** [comment]
@mrlioncub I was not able to reproduce. Could you please provide your YAML file and pipelines logs?

**Comment by mrlioncub** [comment]
@max-zaytsev ok

1. Project name or Repo name must include space!
2. Pool: windows
3. pipeline:
```yaml
pool:
  vmImage: 'windows-2019'

variables:
  DECODE_PERCENTS: false

steps:
- checkout: none
- script: "echo $(BUILD.REPOSITORY.URI) && echo DECODE_PERCENTS:$(DECODE_PERCENTS)"
```
Example, my url repo: https://xxx.visualstudio.com/Test%20Space/_git/Test%20Space 
Command Output:
```
https://xxx.visualstudio.com/Test0Space/_git/Test0Space 
DECODE_PERCENTS:false
```
