### ISSUE TITLE
Negative Patterns not working when Downloading Pipeline Artifacts

### ISSUE THREAD

**Issue by tknerr** [microsoft/azure-pipelines-agent#3755]
## Agent Version and Platform

* Agent version 2.198.3
* Azure DevOps Services, Download Pipeline Artifacts task version 2.198.0
* Ubuntu-20.04 OS

## Azure DevOps Type and Version
https://dev.azure.com 

## What's not working?

When specifying multiple patterns for the [DownloadPipelineArtifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops) task the patterns seem to be correctly passed to the agent, but the filtering / pattern matching does not seem to work properly, especially when more than one negative patterns (prefixed with `!`) is used.

Given the following artifacts and files:
```
job_a_results:
   out/bin/x64/a.bin
   out/logs/foo/bar/log.txt
   out/reports/job-a-report.txt
```

Patterns which **work as expected**:

* `"**/reports/**"` - include only reports (single include pattern)
* `"**/reports/**\n**/logs/**"` - include only reports and logs (multiple include patterns)
* `"!**\n**/reports/**\n**/logs/**"` - exclude all, then include reports and logs (exclude first, then multiple include pattern, equivalent to the above)
* `"!**/logs/**"` - exclude logs (single exclude pattern)

Patterns which **don't work** (i.e. they don't filter the artifacts properly and download everything):

* `"!**/logs/**\n!**/reports/**"` - exclude logs and reports (multiple exclude patterns)
* `"**\n!**/logs/**"` - include all, then exclude logs (include first, then exclude pattern)
* `"!**/(logs|reports)/**"` - exclude logs and reports (attempted via a single pattern) 
* `"**/!(logs|reports)/**"` - exclude logs and reports (another attempt using a single pattern) 

Repro case:

```yml
pool:
  vmImage: ubuntu-20.04

variables:
  System.Debug: true

stages:
- stage: Build
  jobs:
  - job: job_a
    steps:
    - checkout: none
    - script: |
        rm -rf out/
        mkdir -p out/bin/x64 && date > out/bin/x64/a.bin
        mkdir -p out/logs/foo/bar && date > out/logs/foo/bar/log.txt
        mkdir -p out/reports && date > out/reports/job-a-report.txt
    - publish: $(Build.SourcesDirectory)
      artifact: job_a_results

- stage: Package
  jobs:
  - job: package
    steps:
    - checkout: none
    - script: rm -rf $(Pipeline.Workspace)/download*
 
    # exclude multiple patterns - doesn't work
    - task: DownloadPipelineArtifact@2
      inputs:
        path: $(Pipeline.Workspace)/download-2
        patterns: "!**/logs/**\n!**/reports/**"
    - script: find $(Pipeline.Workspace)/download-2 -print
    # include single pattern - works
    - task: DownloadPipelineArtifact@2
      inputs:
        path: $(Pipeline.Workspace)/download-3
        patterns: "**/reports/**"
    - script: find $(Pipeline.Workspace)/download-3 -print
    # exclude all +  include single - works
    - task: DownloadPipelineArtifact@2
      inputs:
        path: $(Pipeline.Workspace)/download-4
        patterns: "!**\n**/reports/**"
    - script: find $(Pipeline.Workspace)/download-4 -print
    # include multiple patterns - works
    - task: DownloadPipelineArtifact@2
      inputs:
        path: $(Pipeline.Workspace)/download-5
        patterns: "**/reports/**\n**/logs/**"
    - script: find $(Pipeline.Workspace)/download-5 -print
    # exclude all + include multiple - works
    - task: DownloadPipelineArtifact@2
      inputs:
        path: $(Pipeline.Workspace)/download-6
        patterns: "!**\n**/reports/**\n**/logs/**"
    - script: find $(Pipeline.Workspace)/download-6 -print
    # exclude single - works
    - task: DownloadPipelineArtifact@2
      inputs:
        path: $(Pipeline.Workspace)/download-7
        patterns: "!**/logs/**"
    - script: find $(Pipeline.Workspace)/download-7 -print
    # include all + exclude single - doesn't work
    - task: DownloadPipelineArtifact@2
      inputs:
        path: $(Pipeline.Workspace)/download-8
        patterns: "**\n!**/logs/**"
    - script: find $(Pipeline.Workspace)/download-8 -print
    # exclude multiple - doesn't work
    - task: DownloadPipelineArtifact@2
      inputs:
        path: $(Pipeline.Workspace)/download-9
        patterns: "!**/logs/**\n!**/reports/**"
    - script: find $(Pipeline.Workspace)/download-9 -print
    # exclude multiple (via single pattern) - doesn't work
    - task: DownloadPipelineArtifact@2
      inputs:
        path: $(Pipeline.Workspace)/download-10
        patterns: "!**/(logs|reports)/**"
    - script: find $(Pipeline.Workspace)/download-10 -print
    # exclude multiple (via single pattern, 2nd try) - doesn't work
    - task: DownloadPipelineArtifact@2
      inputs:
        path: $(Pipeline.Workspace)/download-11
        patterns: "**/!(logs|reports)/**"
    - script: find $(Pipeline.Workspace)/download-11 -print
```
