### ISSUE TITLE
How to prevent creating a new _work folder at each stage?

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [microsoft/azure-pipelines-agent#3789]
Hi everyone.
I have a problem with the azure pipeline stages.
the problem is azure pipeline stages will create a new folder for each stage and I will lose every source that I checkout before.

For example, I have these stages:
1. Checkout
2. Build
3. Tests
4. Deploy
5. etc

the problem is I checkout everything in stage 1 then when I want to build them in stage 2 it's getting the error because stage 1 is in _work\1 and stage 2 is in _work\2 and every resource is in _work\1 that's why I'm getting error in stage 2.

if I move all of them in one stage, everything is ok and every job runs successfully!

my example yml file:

```

trigger:
- Develop

resources:
  repositories:
  - repository: Libraries
    type: git
    name: Libraries
  - repository: Core2
    type: git
    name: Core2
stages:
  - stage: CheckProject
    displayName: Check out
    jobs:
     - job: Checkout
       steps:
        - checkout: self
          path: Projects/Cores/Core1
        - checkout: Core2
          path: Projects/Cores/Core2
        - checkout: Libraries
          path: Projects/Libraries
        
        - powershell: |
                      Remove-Item $(Pipeline.Workspace)/Github/SignalGo-full-net -Force -Recurse -ErrorAction SilentlyContinue
                      git clone --branch netstandard https://github.com/SignalGo/SignalGo-full-net.git Github/SignalGo-full-net
          name: PullSignalGo
          workingDirectory: $(Pipeline.Workspace)

        - task: UseDotNet@2
          displayName: Install .NET Core 6.x SDK
          inputs:
            packageType: 'sdk'
            version: '6.x'
            installationPath: $(Agent.ToolsDirectory)/dotnet
        - task: UseDotNet@2
          displayName: Install .NET Core 5.x SDK
          inputs:
            packageType: 'sdk'
            version: '5.x'
            installationPath: $(Agent.ToolsDirectory)/dotnet
  - stage: Build
    dependsOn: CheckProject
    displayName: Build
    jobs:
     - job: Build
       steps:
        - task: DotNetCoreCLI@2
          name: Build
          inputs:
            command: 'build'
            workingDirectory: $(Pipeline.Workspace)/Projects/Cores/Core1
            arguments: 'Core1.sln'
  - stage: Tests
    dependsOn: Build
    displayName: Tests
    jobs:
     - job: Tests
       steps:
        - task: DotNetCoreCLI@2
          name: Test
          inputs:
            command: 'test'
            workingDirectory: $(Pipeline.Workspace)/Projects/Cores/Core1
            arguments: 'Core1.sln --logger "console;verbosity=detailed"'
```

the main issue comes from:
https://github.com/MicrosoftDocs/azure-devops-docs/issues/11989

**Comment by KonstantinTyukalov** [comment]
Hi, Ali. Thank you for providing information. We will take a look at it soon.

**Comment by denis-tikhomirov** [comment]
Hello @Ali-YousefiTelori,
Jobs and stages in pipelines are isolated instances, each new started job uses new one agent. Key concepts of pipelines are provided in this [article](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops). Only steps in one jobs are allowed to be started on the same agent and have common work directory.
Sometimes they can use the same agent in case it's only available agent, but it's not a rule, it's just a forced measure or a coincidence. And if one or several jobs require results of any previous job, then the results of job must be passed by storing them in available storages/services, e.g. store as Azure Artifact or other package to feed, push updates to repo or save to share or S3 instance.

**Comment by Ali-YousefiTelori** [comment]
Hello @denis-tikhomirov Thanks for your reply.
every job in this example happens in the same folder when I make stages every job in each stage will run in a new folder, it's not random happens, is this scenario ok or something is wrong?

**Comment by max-zaytsev** [comment]
@Ali-YousefiTelori Yes, this is expected behavior since the working folder depends on the sources you are going to use in your job (i.e. depends on the checkout steps). Please see this article about source mappings: https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/jobdirectories.md#source-mappings

You could probably resolve your issue by adding  the same checkout steps to Tests and Build jobs. In this case, the jobs will use the same working directory (if you run them on a single agent)
```yaml
        - checkout: self
          path: Projects/Cores/Core1
        - checkout: Core2
          path: Projects/Cores/Core2
        - checkout: Libraries
          path: Projects/Libraries
```

More info about multi-repo-checkout: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops
