### ISSUE TITLE
Eq() function does not evaluate boolean parameters and variables transitively

### ISSUE THREAD

**Issue by DanielBMann9000** [microsoft/azure-pipelines-agent#3860]
The Azure Pipelines YAML engine does not evaluate comparisons between boolean parameters and variables containing boolean values in a transitive fashion.

Observe:
``` 
parameters:
- name: BoolParameter
  type: boolean
  default: false
variables: 
- name: BoolVariable
  value: false
- name: TransitiveVarParam
  value: ${{ eq(variables.BoolVariable, parameters.BoolParameter) }}
- name: TransitiveParamVar
  value: ${{ eq(parameters.BoolParameter, variables.BoolVariable) }}
trigger: none
pool:
  vmImage: windows-latest
jobs:
- job: A
  steps:
    - checkout: none
    - script: |
        echo ${{ variables.TransitiveParamVar }}
        echo ${{ variables.TransitiveVarParam }}
```

The output of this script will be

```
false
true
```

So essentially,

```
'false' == false = false
false == 'false' == true
```

This makes using the `boolean` type for parameters **completely useless** for any reasonably complex scenario. I'm expecting it won't be fixed because fixing it would constitute a major breaking change, but I feel it's definitely worth reporting.
