### ISSUE TITLE
Add ability to not fetch tags in checkout

### ISSUE THREAD

**Issue by jmarolf** [microsoft/azure-pipelines-agent#3887]
## What's not working?

The default `checkout` task that ships from this repo fetches all tags by default and is not configurable.

https://github.com/microsoft/azure-pipelines-agent/blob/98fc095611f9af644eb7440a42d0acd48ec9936b/src/Agent.Plugins/GitCliManager.cs#L189-L191

furthermore, because it manually specifies `--tags` on the commandline it overrides any `remote.origin.tagOpt==--no-tags` that may be set.

Our git repo has many tags to the point that this option doubles checkout time unnecessarily. I would like a new option to be added called `fetchTags` that defaults to `true` but can be set to false. 

```yaml
steps:
  - checkout: self
    clean: true
    fetchDepth: 1
    fetchTags:false
```
