### ISSUE TITLE
##vso[task.setvariable has varying results with the same variables in different builds 

### ISSUE THREAD

**Issue by promicroNL** [microsoft/azure-pipelines-agent#3965]
## Agent Version and Platform
Version of your agent? 2.206.1

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

https://dev.azure.com/ATS-Global-Products/

## What's not working?
Issue was first posted on https://github.com/microsoft/azure-pipelines-task-lib/issues/866
The results of using Powershell to Write-Host ##vso[task.setvariable is varying when using the environment variable name, e.g. CONNECTIONSTRING_LOGGINGCONNECTION
When using the original variable name,  ConnectionString.LoggingConnection, it works like a charm.

I stumbled up on to this problem while looping through the environment variables. I worked around the problem and solved my challenge differently. But this issue could still be a problem for others.

I tested this behaviour in YAML, but also in the classic pipeline.

### Expected behaviour
An updated variable or an error why the update did not work

### Actual behaviour
On updating 7 variables, ever build another number of successful updates are there, but never 7.

### Steps to reproduce
1.  Create a yaml pipeline
2.  Paste in this code:
```yml

variables:
  connectionString.Common: Data Source=APISRV,3333;Initial Catalog=Logging;Integrated Security=False;User
      Id=;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office
  connectionString.ConnectionString1: Data Source=APISRV,3333;Initial Catalog=Css;Integrated Security=False;User
      Id=;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office
  connectionString.Logging: Data Source=APISRV,3333;Initial Catalog=Logging;Integrated Security=False;User
      Id=;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office
  connectionString.Framework: Data Source=APISRV,3333;Initial Catalog=FWD;Integrated Security=False;User
      Id=;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office
  connectionString.LoggingVerbose: Data Source=APISRV,3333;Initial Catalog=Logging;Integrated Security=False;User
      Id=;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office
  connectionString.Test: Data Source=APISRV,3333;Initial Catalog=Test;Integrated Security=False;User
      Id=;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office
  connectionString.Production: Data Source=APISRV,3333;Initial Catalog=Production_;Integrated Security=False;User
      Id=;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office

trigger:
- master

pool:
  name: Pool

stages:
- stage: A
  jobs:
  - job: A1
    steps:
      - powershell: |
          Write-Host "##vso[task.setvariable variable=CONNECTIONSTRING_COMMON;]Data Source=SomeTestServer,3333;Initial Catalog=Common;Integrated Security=False;User Id=<ReleaseUserId>;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office"
          Write-Host "##vso[task.setvariable variable=CONNECTIONSTRING_CONNECTIONSTRING1;]Data Source=SomeTestServer,3333;Initial Catalog=ConnectionString1;Integrated Security=False;User Id=<ReleaseUserId>;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office"
          Write-Host "##vso[task.setvariable variable=CONNECTIONSTRING_FRAMEWORK;]Data Source=SomeTestServer,3333;Initial Catalog=Framework;Integrated Security=False;User Id=<ReleaseUserId>;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office"
          Write-Host "##vso[task.setvariable variable=CONNECTIONSTRING_LOGGINGCONNECTION;]Data Source=SomeTestServer,3333;Initial Catalog=Logging;Integrated Security=False;User Id=<ReleaseUserId>;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office
          Write-Host "##vso[task.setvariable variable=CONNECTIONSTRING_LOGGINGVERBOSE;]Data Source=SomeTestServer,3333;Initial Catalog=LoggingVerbose;Integrated Security=False;User Id=<ReleaseUserId>;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office"
          Write-Host "##vso[task.setvariable variable=CONNECTIONSTRING_PRODUCTION;]Data Source=SomeTestServer,3333;Initial Catalog=Production;Integrated Security=False;User Id=<ReleaseUserId>;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office"
          Write-Host "##vso[task.setvariable variable=CONNECTIONSTRING_TEST;]Data Source=SomeTestServer,3333;Initial Catalog=Test;Integrated Security=False;User Id=<ReleaseUserId>;Password=<ReleasePassword>;MultipleActiveResultSets=True;Application Name=Office"
        displayName: Update variables
      - task: PowerShell@2
        displayName: Check the results
        inputs:
          targetType: 'inline'
          script: 'Get-ChildItem -Path Env:\ | Where-Object { $_.name -like ''ConnectionString_*'' }'
          pwsh: true

```

4. Run several builds
5. Compare the results from the "check the results" task
