### ISSUE TITLE
Feature request: Allow setting working directory for container jobs to allow DooD (docker outside of docker) correct path mapping on host

### ISSUE THREAD

**Issue by paul-ri** [microsoft/azure-pipelines-agent#4065]
## Agent Version and Platform
* Agent version: `2.213.2`
* OS of the machine running the agent: Linux:ubuntu-latest

## Azure DevOps Type and Version
* dev.azure.com: https://dev.azure.com/NHSGGC/MDU

## What's not working?

A feature request & maybe a bug:

1. I'd like to set the working directory of my container jobs to something else than the currently unchangeable `/__w/1/s` folder. Ideally map it to the same as the host `/home/vsts/work/1/s`. I'd be best if I could change it for all jobs and / or scripts.
2. Bug?: The [`workingDirectory` option of a `script:`](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-script?view=azure-pipelines) doesn't change the container's working directory and will always start at `/__w/1/s`. I would have expected that option to change the container's working directory

Looking at the volumes mounted in the container, I see that the working directory is set by a file from this repository here:

https://github.com/microsoft/azure-pipelines-agent/blob/ceb7d6cb16b0460c38fbb14c65a85f313cc8e88b/src/Misc/layoutbin/containerHandlerInvoker.js.template#L11

Can it be made, somehow, a user-changeable parameter please?

**Use case:**

Docker compose volumes allows to mount folder using a relative path. As explained in your doc, [Mounting volumes using Docker within a Docker container](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#mounting-volumes-using-docker-within-a-docker-container) means if running a docker compose file within a container job, the mounted paths need to exist on the pipeline host, not on the container.

**Example:**

Let's name:
* 'host': the pipeline host (here ubuntu)
* 'build-container': the container started by the container job. It shares the docker socket of the 'host' [by default](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-containers-container?view=azure-pipelines) (and that's what I want)
* 'dood-app-container': the _"docker outside of docker"_ container started inside the 'build-container' that will actually run with from the 'host' docker daemon

This means with a compose file like such started by the 'build-container':
```compose
service:
  dood-app-container:
    # [...]
    volumes:
      - ./bar_folder:/opt/baz
```
Given the working directory of the 'build-container' is `/__w/1/s`, it will try to mount `/__w/1/s/bar_folder` into the 'dood-app-container' at `/opt/baz`. Yet since this is using the 'host' docker daemon, the source path needs to map to a folder on the 'host', which it doesn't. It only exist at `/home/vsts/work/1/s/bar_folder`.

If the working directory of 'build-container' could be changed to `/home/vsts/work/1/s` then I'd be fine!

**Workaround:**

I'm having success with this: My workaround at the moment is to mount the host working dir in the `resources:` definition and to `cd` to the right folder in all my scripts where I use docker-compose:

```yaml
resources:
  containers:
  - container: build-container
    image: foobar.azurecr.io/builder:unstable
    endpoint: SomeRegistry
    volumes:
      - "/home/vsts/work/1:/home/vsts/work/1"

jobs:
- job: Setup
  container: build-container
  steps:
  - script: |
      echo PWD is
      pwd
      # prints '/__w/1/s'  -> I need an option for it to be '/home/vsts/work/1/s' instead
     cd /home/vsts/work/1/s
     docker compose up
```

It's not ideal as it means we'll have to never forget this annoying `cd /home/vsts/work/1/s` line

I do not want to change our docker-compose.yaml files to prefix all relative path with an environment variable. I'd like to avoid changing our source code to accommodate for an Azure quirk.

**Failed attempts:**
* Using a script's `workingDirectory` option. I suspect that only affects the host, no the container. But it's not clear in the doc and it should change the container's working directory in my opinion.
* Changing Azure env vars like `AGENT_BUILDDIRECTORY`: the relevant ones are read only.
* Changing the `stdinData.workDir` in `/__w/_temp/containerHandlerInvoker.js`: looks like it's read only or reset in between `script:`

**Background:**

We're trying to move from Jenkins to Azure DevOps at work. Instead of creating an Azure virtual machine image and having to figure out how to spawn custom EC2-like agents on Azure (like we do for Jenkins agents on AWS), I'd like to be able to do Docker outside of Docker and run our Makefiles (which build/test/deploy docker apps) inside a container.

I hope this is clear : ) Thanks!

**Comment by vmapetr** [comment]
Hi @paul-ri, thanks for your request! 
We've added this issue to our backlog. We'll take a look at it once we have enough capacity.

**Comment by Dave562CZ** [comment]
This is also needed for correct function of testcontainers with volumes: https://www.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/

**Comment by paul-ri** [comment]
Still very much needed. We've had to add some workarounds where we use a template for our Ci jobs that injects code in steps that are scripts to change the working directory:

```yaml
parameters:
- name: buildStep
  displayName: "Step to be run"
  type: step
  default: []
- name: useDockerBuilder
  displayName: 'Use custom docker builder image'
  type: boolean
  default: false
- name: workingDirectory
  displayName: 'Working directory of the step'
  type: string

steps:
  - ${{ each field in parameters.buildStep }}:
      ${{ if ne(field.key, 'inputs') }}:
        ${{ field.key }}: ${{ field.value }}
      ${{ else }}:
        inputs:
          ${{ each input_field in field.value }}:
            ${{ if eq(input_field.key, 'script') }}:
              script: |
                if [[ ( '${{ parameters.useDockerBuilder }}' == 'True' ) && ( '${{ field.target }}' != 'host' ) ]]; then
                  # Default working directory is '/__w/1/s'
                  cd /home/vsts/work/1/s/${{ parameters.workingDirectory }}
                fi
                ${{ input_field.value }}
            ${{ elseif not(and(parameters.useDockerBuilder, eq(input_field.key, 'workingDirectory'))) }}:
              ${{ input_field.key }}: ${{ input_field.value }}
```

**Comment by alegend4u** [comment]
It'd be good to have `workingDirectory` attribute at `job` level too.

**Comment by paul-ri** [comment]
Still needed and still using workarounds mentioned above. It's not great to do complex things in YAML, but it works.

**Comment by paul-ri** [comment]
_A new workaround and a new behaviour change request in that comment:_

@jack1902 , what volumes have you mounted on your container?

I'm having a problem where the host user is not `vsts`, as I've been given an agent that runs on a ubuntu VM.
Meaning the assumption I was making for a cloud agent are not valid anymore: paths & usernames are different.

Your solution sounded great for me, unfortunately, the workspace gets cleaned when checking out the code; and I can't easily inject your step that create a file in the right place.

So as a new workaround (to what already is a workaround): **I'm saving the current path in a variable**!

Problem is, the variable value created on the host, **is changed** when read back on the container. That's really not what I would have expected. I'd like to suggest this is documented clearly or removed.

Here's the example illustrating the issue: 1st step creates variables on the host, 2nd steps prints them on the host, 3rd prints them on the container (and are modified by Azure DevOps)
```yaml
  steps:
    - script: |
# The value will be changed by Azure when in the container
        echo '##vso[task.setvariable variable=host_working_directory;]$(pwd)'
# The value will be changed by Azure when in the container, despite the suffix
        echo "##vso[task.setvariable variable=test_0;]$(pwd)AAA"
# The value does NOT get changed by Azure when in the container, thanks to the prefix
        echo "##vso[task.setvariable variable=test_1;]AAA$(pwd)"
# The value does NOT get changed by Azure when in the container, thanks to being encoded
        echo "##vso[task.setvariable variable=test_2;]$(bash -c 'pwd | base64')"
# Getting trouble using this despite being copied from the doc
        echo "##vso[task.setvariable variable=myOutputJobVar;isoutput=true]this is the same job too"
      displayName: 'Saving host working directory'
      target: host
    - script: |
        echo "Agent.BuildDirectory: $(Agent.BuildDirectory)"
        echo "Build.SourcesDirectory: $(Build.SourcesDirectory)"
        echo "host_working_directory: $(host_working_directory)"
        echo "test_0: $(test_0)"
        echo "test_1: $(test_1)"
        echo "test_2: $(test_2)"
        echo "test_2 decoded : $(echo $(test_2) | base64 --decode)"
        echo "setOutput.myOutputJobVar: $(setOutput.myOutputJobVar)"
      displayName: 'Checking variables on host'
      target: host
    - bash: |
        echo "Agent.BuildDirectory: $(Agent.BuildDirectory)"
        echo "Build.SourcesDirectory: $(Build.SourcesDirectory)"
        echo "host_working_directory: $(host_working_directory)"
        echo "test_0: $(test_0)"
        echo "test_1: $(test_1)"
        echo "test_2: $(test_2)"
        echo "test_2 decoded : $(echo $(test_2) | base64 --decode)"
        echo "setOutput.myOutputJobVar: $(setOutput.myOutputJobVar)"
      displayName: 'Checking variables on Docker'
```

| Variable values on the host | Variable values on the container |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/2b6d4fc4-4401-40bf-9b17-a747ae8d17d6) | ![image](https://github.com/user-attachments/assets/7b23c6f4-fb99-4ed9-b468-57f5b1ef13fd) |

So I'm storing the current working directory on the host in variable but encoded with base64 and decode it in the container.

And these are the volumes I'm mounting in the container. It's not ideal
```yaml
        volumes:
          # 'vsts' is the default user in Azure pipelines default cloud agent
          - "/home/vsts/work/1:/home/vsts/work/1"
          # Our VM hosts are setup with a 'locadmin' user
          - "/home/locadmin:/home/locadmin"
```

**Comment by paul-ri** [comment]
Still an issue! Still complex workarounds.

**Comment by sluebbert** [comment]
FWIW, I think this feature request would help solve some complexity for us too.

If we could force the container workspace to always be `/__w/` or some other constant path, our multi job / multi stage building, testing, and code analysis tools would function under the assumption they are all running sequentially on the same environment if we ship artifacts across the stages.

The automatic, default container workspace of `/__w/{numberFromHostWorkspace}` means that jobs that land on different agents have different absolute file paths to source files which causes confusion across tools trying to work together or merge results. Containers gives us an excellent way to abstract that issue away, we are just missing this last piece to make it easier.

Example:
```yml
container: 
  image: nameofimage:latest
  workspace: /__w/
```
It seems like we don't have access to job related variables at this point yet such as `Pipeline.Workspace` from my quick testing, so I have no guesses on the syntax to get your original `/home/vsts/work/1/s` example 😖. Maybe a behavior keyword instead? One of `["default", "matchHost", "constant"]`. I dream on... 🤔
