### ISSUE TITLE
Multiple checkouts on self-hosted agents results in error

### ISSUE THREAD

**Issue by Meandron** [microsoft/azure-pipelines-agent#4070]
## Agent Version and Platform
2.213.2

OS of the machine running the agent? 
Ubuntu

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/PDPQ-DMP

## What's not working?
We plan to migrate from Microsoft-hosted agents to self-hosted agents.
With MSFT agents, we checked out the git repository (-> in our DMP Project) by using:

``` yaml
checkout: self
```
So, on every job (as a fresh, clean VM is used for every new job), we have that checkout step at the beginning. It works without issues.
Now, when specifying the self-hosted agent pool, the second checkout command fails with errror 400:

Everything works well on first run:
![first checkout success](https://user-images.githubusercontent.com/5312438/204599007-a00b51ff-75c0-4d93-9016-d090f69c3cc2.png)

But on second run, different job:
![second run, fail](https://user-images.githubusercontent.com/5312438/204599805-673bbeaf-eb58-4cb0-9c36-78a978a7b105.png)

What might influence it: The project name in our organisation contains whitespaces, but no issues with MSFT agents here.
EDIT 19/Dec/2022: With MSFT, we get a fresh VM every time, like the first working checkout on self-hosted agents...

There is a space after DMP, resulting in a strange escape sequence for the origin remote: %AZP2520, whereas at other locations, its %20 as expected.

**Comment by max-zaytsev** [comment]
Hi @Meandron Thanks for reporting this.
We are currently working on higher priority issues. But we'll get back to that soon.

**Comment by Meandron** [comment]
@max-zaytsev 
We could figure it out meanwhile ourselves. 

```
- task: Bash@3
  inputs:
    targetType: "inline"
    script: |
      git config --global --unset-all http.extraheader || true
      git config --global --unset-all remote.origin.fetch || true
    failOnStderr: true
  continueOnError: true
  condition: always()
- checkout: self
```

That way, multiple checkouts work for us.
