### ISSUE TITLE
Missing folder when checking out multiple repositories with the same name

### ISSUE THREAD

**Issue by schenker** [microsoft/azure-pipelines-agent#4087]
## Agent Version and Platform
3.213.2 / Linux

## What's not working?
Considering this example:
``` 
resources:
  repositories:
    - repository: MyRepo
      type: git
      name: myrepo
...

steps:
  - checkout: MyRepo
    path: s/myrepo
  - checkout: MyRepo
    path: s/myrepo2
```
The first `checkout` steps checks out `MyRepo` to `s/myrepo`. According to the logs, the second checkout step checks out `MyRepo` to `s/myrepo` and then moves it to `s/myrepo2`: `"Repository is current at '/home/vsts/work/1/s/myrepo', move to '/home/vsts/work/1/s/myrepo2'."`

The result after the second checkout is that `s/myrepo2` exists, but `s/myrepo` does not exist.
