### ISSUE TITLE
Azure Build Pipelines not adding installed software to path

### ISSUE THREAD

**Issue by Data-Alchemy** [microsoft/azure-pipelines-agent#4091]
Agent Version and Platform
Version of your agent? 2.213.2

OS of the machine running the agent? 
Agent Type: Self Hosted
Agent.OS : Windows_NT
Agent.OSArchitecture:  X64
Agent.OSVersion: 10.0.22000

Azure DevOps Type and Version
dev.azure.com (Cloud)

What's not working?
When installing any software on self hosted agent using build pipeline software does not get added to path variable for the agent

Description

When using a build pipeline to try to install software on a self hosted agent the installed software does not get added to path variable and therefore am not able to call the software by name (ie python --version, poetry --version  java -version or choco --version)).

I have tried to add to path variable using several methods and nothing adds to path variable in a way that i can call application from release pipeline.

test 1 Using task.prependpath:
Write-Host "##vso[task.prependpath]$env:C:\Users\<some_user>\AppData\Roaming\Python\Scripts\poetry.exe"

test 2 Using task.setvariabl:  

Write-Host "##vso[task.setvariable variable=poetry;isoutput=true]C:\Users<some_user>\AppData\Roaming\Python\Scripts\poetry.exe"
  
test 3 Using env setting of task: 
env:
              poetry: C:\Users\FalconDevOpsUser\AppData\Roaming\Python\Scripts\poetry.exe

Expected behavior
running a application name command should properly execute said command 

ex:
python --version

Python 3.x

Actual behavior

The term '<some application name>' is not recognized as the name of a cmdlet, function, script file, or operable program.

Steps to replicate : 
create empty build definition

```
trigger: none

pool:
  name: MySelfHosted

stages:
  - stage: BuildAndTest
    displayName: Build and Test
    jobs:
      - job: BuildWithPoetry
        displayName: Build with Poetry

        steps:
          
          - task: PowerShell@2
            displayName: Install Chocolatey
            inputs:
              targetType: inline
              script: |
                Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
            env:
              CHOCO_HOME: 'C:\Users\FalconDevOpsUser\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall'

          - task: PowerShell@2
            displayName: Install Python
            inputs:
              targetType: inline
              script: |
                choco install -y python
          
          - task: PowerShell@2
            displayName: Install Poetry
            inputs:
              targetType: inline
              script: |
                (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content |py -

          - task: PowerShell@2
            displayName: Test Installs
            inputs:
              targetType: inline
              script: |
                python --version
                poetry --version
                choco --version
```
