### ISSUE TITLE
Agent logs have "1" replaced with "*"

### ISSUE THREAD

**Issue by arp-mbender** [microsoft/azure-pipelines-agent#4094]
## Agent Version and Platform
'2.2***3.2' Hey, since 1s are replaced with ***, you can figure it out! :)
Agents are hosted in Docker Containers on Windows 2022

## Azure DevOps Type and Version
On-prem Azure DevOps Server 2020 Update 1.2

## What's not working?
Logs have `1`s replaced with `***`.
![image](https://user-images.githubusercontent.com/60735180/208118942-5edbaa7e-031d-4adf-9fa5-816561197cff.png)

There aren't any secrets in the pipeline I was testing this with, so I'm unsure why this is happening. I've tried the `AZP_IGNORE_SECRETS_SHORTER_THAN` knob, but it seems the agent doesn't recognize this.

**Comment by ismayilov-ismayil** [comment]
Duplicate: [https://github.com/microsoft/azure-pipelines-agent/issues/4094](url)

**Comment by arp-mbender** [comment]
Did you just link this to itself? 😆

**Comment by ismayilov-ismayil** [comment]
Hi @arp-mbender, thanks for reporting. Could you please share your pipeline yaml file? If there is any confidential data, please, replace it with any tag or mask

**Comment by arp-mbender** [comment]
No problem. Here's the pipeline definition:

```
trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - readme.md
      - examples/*

pool: 
  name: DockerPool

variables:
  ImageName: 'devops-agent-win-generic'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    timeoutInMinutes: 0
    displayName: Build and push Docker image
    steps:
    - task: gitversion/execute@0
      displayName: GitVersion
    - task: Docker@2
      displayName: Build the image
      inputs:
        command: build
        addPipelineData: false
        arguments: '--force-rm -m 3g'
        Dockerfile: '**/DockerFile'
        repository: '<internal.repo.url>/$(ImageName)'
        tags: |
          latest
          $(Build.BuildId)
    - task: Docker@2
      displayName: Push the image
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      inputs:
        command: 'push'
        containerRegistry: DockerHub
        addPipelineData: false
        repository: $(ImageName)
        tags: |
          latest
          $(Build.BuildId)

```
