### ISSUE TITLE
Step target attribute does not always work

### ISSUE THREAD

**Issue by christoe** [microsoft/azure-pipelines-agent#4131]
## Agent Version and Platform
Hosted agent: ubuntu-latest
CmdLine: 2.212.0

## Azure DevOps Type and Version
dev.azure.com 

## What's not working?
I have a job that should run integration tests, for these tests to run I need a database running alongside the application. I've set this up as follows:

```yaml
[...]
  - job: integration_tests
    displayName: Run integration tests
    pool:
      vmImage: ubuntu-latest
    services:
      postgis: postgis
    container: 
      image: $(imageRepository):$(tag)
      endpoint: '<endpoint>'
    steps:
    - script: <script_that_initializes_postgres>
      target: 
        container: postgis
      displayName: "Initialize postgres"
    - script: |
        pytest --cov --cov-report xml:coverage.xml
      displayName: "Test: pytest"
[...]
```
Expected result is that `<script_that_initializes_postgres>` runs in a shell on the container `postgis` defined also in the yaml, and then pytest is started in the container defined within the job. This turns out not to be the case. 

Adding some debug lines:
```yaml
[...]
    steps:
    - script: docker ps
      target: host
    - script: |
        cat /etc/hostname
        <script_that_initializes_postgres>
      target: 
        container: postgis
[...]
```
Output from first script:
```
CONTAINER ID   IMAGE                                COMMAND                  CREATED         STATUS         PORTS                                       NAMES
69e3ac9ed8e7   postgis/postgis:14-3.3-alpine        "docker-entrypoint.s…"   4 seconds ago   Up 3 seconds   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   postgis_postgispostgis1433alpine_f56ed5
c90348663954   ***/<image>:<tag>   "/__a/externals/node…"   5 seconds ago   Up 4 seconds   80/tcp         
```

And from the second script:
```
c90348663954
su: user postgres does not exist or the user entry does not contain all the required fields <<-- this is due to <script_that_initializes_postgres> running in the wrong container
```

As seen above, the `docker ps` command executes successfully on the agent vm, but the script that's supposed to run in the postgis container actually runs on the `<image>:<tag>` container (i.e. the one defined in the job). From this I draw the conclusion that `target: host` indeed works as expected, but `target: <container>` or `target: container: <container>` as in the example above (I tried both) does not do what the documentation tells me it should.

No other obvious errors in the pipeline, yaml validates and all tasks run - apart from the script running in the wrong container. Am I misreading the documentation (https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/target?view=azure-pipelines#target-container-commands-settablevariables) or is there a bug somewhere?

**Comment by DmitriiBobreshev** [comment]
Hi @christoe, the problem really exists because when you're using the keyword **service**, Azure DevOps sends it to the agent as a [SidecarContainers ](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Worker/ExecutionContext.cs#L575), and when you're using keyword **target: container: containerName** it searches through ["main" containers](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Worker/ExecutionContext.cs#L863). We will implement behaviour to be able to run steps inside service containers. Thank you for the feedback!

**Comment by christoe** [comment]
@DmitriiBobreshev: Thanks for fast feedback! Is there a good workaround while the fix is being prepared? I wasn't able to get things going without the service keyword?

**Comment by DmitriiBobreshev** [comment]
@christoe, unfortunately, there is no easy way to do it without services, you could use other containers in the job, like [in example](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/target?view=azure-pipelines#examples) without service, but for communication, there are limited [agent's variables](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Microsoft.VisualStudio.Services.Agent/Constants.cs#L285) to use.

Another way is to run the command through docker exec, in this case, the pipeline could be like this:
```
resources:
  containers:
  - container: nginx
    image: nginx
    options: --name nginx-test
    ports:
    - 8080:80
    env:
      NGINX_PORT: 80
  - container: ubuntucontainer
    image: ubuntu:latest
    options:  --name ubuntu-test

jobs:
- job: integration_tests
  displayName: Run integration tests
  pool:
    vmImage: 'ubuntu-latest'

  container: ubuntucontainer
  services:
    nginx: nginx
  steps:
  - script: |
      docker ps
    target: host

  - script: |
      cat /etc/hostname
    target: ubuntucontainer

  - script: 
      docker exec -i nginx-test /bin/cat /etc/hostname
    target:
        container: host
```
