### ISSUE TITLE
Variable Build.Repository.Clean not set anymore

### ISSUE THREAD

**Issue by ryan-adler** [microsoft/azure-pipelines-agent#4171]
## Agent Version and Platform
2.217.2

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? 
https://dev.azure.com/ucss

## What's not working?
Even when setting the clean option in the Trigger -> YAML options to enabled, the Build.Repository.Clean variable remains undefined.

## Agent and Worker's Diagnostic Logs
`##[debug]Build.Repository.Clean=undefined`

**Comment by ryan-adler** [comment]
Seems to be a regression of #2770

**Comment by ryan-adler** [comment]
Any update on this?

**Comment by ALTrijssenaar** [comment]
Hitting the same issue!

**Comment by ismayilov-ismayil** [comment]
Hi @ryan-adler 
I was not able to reproduce the issue. 
Could you please confirm that issue still actual? 

This is the sample task to trace the variable:
```
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host $(Build.Repository.Clean)'
```

**Comment by ryan-adler** [comment]
@ismayilov-ismayil 

I just tried creating a new pipeline with the one task ask you describe above, here is the output:
```
Starting: PowerShell
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.220.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\23f22f4a-7f79-4537-97e6-220e2bc0e47f.ps1'"
Build.Repository.Clean : The term 'Build.Repository.Clean' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At D:\a\_temp\23f22f4a-7f79-4537-97e6-220e2bc0e47f.ps1:4 char:14
+ Write-Host $(Build.Repository.Clean)
+              ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Build.Repository.Clean:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
 
##[error]PowerShell exited with code '1'.
Finishing: PowerShell
```

If I manually define the variable, here is the output:
```
Starting: PowerShell
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.220.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\86d6cbd0-bcd1-4edd-a871-984bd7d8f13c.ps1'"
true
Finishing: PowerShell
```

Here is the entire YAML:
```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host $(Build.Repository.Clean)'
```

So indeed, the issue is definitely still relevant.
