### ISSUE TITLE
[enhancement]: podman support

### ISSUE THREAD

**Issue by a-dawg** [microsoft/azure-pipelines-agent#4227]
### Podman support

as podman is becoming the default container runtime on > rhel8, it should be supported
event with using the podman-docker yum package, when using a linux agent and containers in the pipeline spec, I am getting:
````
Error: statfs /var/run/docker.sock: no such file or directory
##[error]Exit code 125 returned from process: file name '/usr/bin/docker', arguments 'create --name curl_networktoolsrhel8_d45264 --label d57d78 --network vsts_network_bfdacacea91c42d2bbb61a467fa03695  -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/opt/azuredevops_agent/1":"/__a/1" -v "/opt/azuredevops_agent/_temp":"/__a/_temp" -v "/opt/azuredevops_agent/_tasks":"/__a/_tasks" -v "/opt/azuredevops_agent/_tool":"/__t" -v "/opt/azuredevops_agent/externals":"/__a/externals":ro -v "/opt/azuredevops_agent/.taskkey":"/__a/.taskkey" xxx/openshift4/network-tools-rhel8 "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"'.
Finishing: Initialize containers

````
````
ls -l  /var/run/docker.sock
lrwxrwxrwx. 1 root root 23 Apr  4 15:35 /var/run/docker.sock -> /run/podman/podman.sock
````

**Comment by DmitriiBobreshev** [comment]
Hi @a-dawg, thank you for the feedback! We'll take a look once we'll have enough capacity.

**Comment by ricksbrown** [comment]
> ### Podman support
> as podman is becoming the default container runtime on > rhel8, it should be supported event with using the podman-docker yum package, when using a linux agent and containers in the pipeline spec, I am getting:
> 
> ```
> Error: statfs /var/run/docker.sock: no such file or directory
> ##[error]Exit code 125 returned from process: file name '/usr/bin/docker', arguments 'create --name curl_networktoolsrhel8_d45264 --label d57d78 --network vsts_network_bfdacacea91c42d2bbb61a467fa03695  -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/opt/azuredevops_agent/1":"/__a/1" -v "/opt/azuredevops_agent/_temp":"/__a/_temp" -v "/opt/azuredevops_agent/_tasks":"/__a/_tasks" -v "/opt/azuredevops_agent/_tool":"/__t" -v "/opt/azuredevops_agent/externals":"/__a/externals":ro -v "/opt/azuredevops_agent/.taskkey":"/__a/.taskkey" xxx/openshift4/network-tools-rhel8 "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"'.
> Finishing: Initialize containers
> ```
> 
> ```
> ls -l  /var/run/docker.sock
> lrwxrwxrwx. 1 root root 23 Apr  4 15:35 /var/run/docker.sock -> /run/podman/podman.sock
> ```

Hi there, you just need to set `mapDockerSocket: false`
See [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job-container?view=azure-pipelines#container-image)

```yaml
container:
  image: string # Required. Container image tag.
  endpoint: string # ID of the service endpoint connecting to a private container registry.
  env: # Variables to map into the container's environment.
    string: string # Name/value pairs
  mapDockerSocket: boolean # Set this flag to false to force the agent not to setup the /var/run/docker.sock volume on container jobs.
  options: string # Options to pass into container host.
  ports: [ string ] # Ports to expose on the container.
  volumes: [ string ] # Volumes to mount on the container.
  mountReadOnly: # Volumes to mount read-only, the default is all false.
    work: boolean # Mount the work directory as readonly.
    externals: boolean # Mount the externals directory as readonly.
    tools: boolean # Mount the tools directory as readonly.
    tasks: boolean # Mount the tasks directory as readonly.
```
