### ISSUE TITLE
[BUG]: vso command with cmd and variables

### ISSUE THREAD

**Issue by cliedelt** [microsoft/azure-pipelines-agent#4301]
### What happened?

RIght now you cannot use vso commands in a cmd. For example:
```
    - task: CmdLine@2
      displayName: 'Create git tag for release'
      inputs:
        script: |
          echo ##vso[build.addbuildtag]%PROJECTVERSION%
```
results in 
```
##[error]A potentially dangerous Request.Path value was detected from the client (%).
```

### Versions

Agent Version: 3.218.0
Windows: 10.0.17763

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)
