### ISSUE TITLE
[enhancement]: Allow parameter default value to utilize another parameter value

### ISSUE THREAD

**Issue by dmcmenamin-kt** [microsoft/azure-pipelines-agent#4314]
### Describe your feature request here

It would be convenient to allow creation of a default parameter value that utilizes the value of another parameter. Something like the following:
``` yaml
parameters:
- name: solutionTarget
  type: string
  default: ''
- name: msBuildArguments
  type: string
  default: -target:${{ parameters.solutionTarget }}
- name: binSourcePath
  type: string
  default: $(Build.SourcesDirectory)/${{ parameters.solutionTarget }}/bin
```

This would allow a convenient syntax for creating a template where parameters have a default value that stems from a single parameter, but still allows the template user to set a different value.

This request is essentially reiterating the request made in #2737. The suggested workaround by @vtbassmatt  was to use variables to create these values that depend on others. In my case, I would like to create templates that are at the scope of a `steplist` or `step`. It is not possible to define variables in these scopes. Instead, I used the workaround suggested by @jtpetty using a task to set variables, which lets me create variables in the context of a `steplist` or `step` template:
```yaml
parameters:
- name: solutionTarget
  type: string
  default: ''
- name: msBuildArguments
  type: string
  default: ''
- name: binSourcePath
  type: string
  default: ''

steps:
- bash: |
    if [ -z "${{ parameters.msBuildArguments }}" ]; then
      echo "##vso[task.setvariable variable=msBuildArgumentsVar]-target:${{ parameters.solutionTarget }}"
    else
      echo "##vso[task.setvariable variable=msBuildArgumentsVar]${{ parameters.msBuildArguments }}"
    fi
    if [ -z "${{ parameters.binSourcePath }}" ]; then
      echo "##vso[task.setvariable variable=binSourcePathVar]$(Build.SourcesDirectory)/${{ parameters.solutionTarget }}/bin"
    else
      echo "##vso[task.setvariable variable=binSourcePathVar]${{ parameters.binSourcePath }}"
    fi
```

As you can see, the syntax is quite cumbersome and it took a lot of trial and error to actually get it working. The creation of the variables in my solution could possibly be simplified, but I played around using the expression `join()` and `coalesce()` functions for an hour with no success. As @jmezach expressed, this seems very complex for such a 'simple' operation. I think something like the syntax in the first block is much easier for pipeline authors to develop/maintain and enhances the value of templates for Azure Pipelines customers.

**Comment by DmitriiBobreshev** [comment]
Hi @dmcmenamin-kt, Thank you for the feedback, unfortunately, since the parameters are in AzDevOps runtime and the agent can't manipulate them, probably you need to write your suggestion on the dev community to add a template expression in the parameters definitions to be able to set default values dynamically.

We understand that expressions might be a little bit tricky, so let me help you with your problem,
probably you better use [the format function](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#format) instead of join to concatenate parameter with a string inside your expression, it might look like this:

```
parameters:
- name: solutionTarget
  type: string
  default: 'someSolutionTarget'
- name: msBuildArguments
  type: string
  default: ''
- name: binSourcePath
  type: string
  default: ''

variables:
  - name: sourceDir
    value: $(Build.SourcesDirectory)
  - name: msBuildArgumentsVar
    value: ${{ coalesce(parameters.msBuildArguments, format('-target:{0}', parameters.solutionTarget)) }}
  - name: binSourcePath
    value: ${{ coalesce(parameters.binSourcePath, format('{0}/{1}/bin', variables.sourceDir, parameters.solutionTarget )) }}

jobs:
- job: 'Example'
  pool:
    vmImage: 'ubuntu-22.04'
  steps:
  - script: | 
      echo "msBuildArgumentsVar: $(msBuildArgumentsVar)" 
      echo "binSourcePath: $(binSourcePath)" 
      echo "sourceDir: $(sourceDir)"
```

and the result will be similar to yours
![image](https://github.com/microsoft/azure-pipelines-agent/assets/106314398/39f8f9f4-126f-4eca-8faa-ef2361e1381f)
