### ISSUE TITLE
[Question]: Agent running with --once in container, with two jobs, shows as offline when second one queued.

### ISSUE THREAD

**Issue by dazinator** [microsoft/azure-pipelines-agent#4338]
### Describe your question

I am running a pipelines agent as a docker container  (swarm) - so that it shows up in pipelines --> environments.

The docker container is run with the `--once` argument and a restart policy with a small delay a mentioned in the docs here: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#start-the-image

```
devops-pipelines-agent:    
    image: foo.azurecr.io/foo/environment-agent:${PIPELINES_AGENT_TAG}
    deploy:
      replicas: 1      
      restart_policy:        
        condition: any
        delay: 1s
    command: --once

```

What I find is that when I have an `azure-pipelines..yaml` with two jobs to be run one after the other, on the agent e.g shortened for brevity:

```
jobs:
  - deployment: thingA
  - deployment: thingB
    dependsOn: thingA
    condition: succeeded()
```

The agent goes offline after the first job, and azure devops then fails the second job due to the agent being "offline"

![image](https://github.com/microsoft/azure-pipelines-agent/assets/3176632/ea09cf42-a7ee-4b66-8da9-8cff2981aaec)

The agent is only offline for a very breif period of time according to the restart policy, a few seconds plus start uptime etc.

I thought I could work around this by scaling theagent to replica's 2. However as both agents are the same environnment, this just causes the jobs to fan oout and be run oon both agents, as oopposed to being queued and picked up by the first available "online".

I like the features of environments agents,and deployment jobs, but this seems like a bug? I could switch too agent pools with replica's 2 and my above suggested workaround should hopefully then work, but this should nnot be necessary?

### Versions

Current agent version: '3.220.5'
Agent running as: 'root'

running pipeline on dev.azure.com

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Version controll system

git (azure devops)
