### ISSUE TITLE
[BUG]: Self hosted agent fills up server storage, does not reuse folder from previous pipeline run

### ISSUE THREAD

**Issue by Geo-Ron** [microsoft/azure-pipelines-agent#4341]
### What happened?

We have three azure self hosted agents running on a single server.

Everything works fine until last week we ran out of disk space on the data disk.

The _work directories for each agent have grown to a size that completely filled up the server's storage.

We have a maintenance schedule set up for the agent pool.

The only instant solution is to RDP into the server and delete all the number folders inside _work.

It looks like as if it is not reusing the git repository from a previous pipeline run anymore.

### Versions

Azure Devops Agens version 3.220.5, Windows server 2019 Std.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Version controll system

devops git repo

**Comment by DenisRumyantsev** [comment]
Hi @Geo-Ron, so, you are using self-hosted Windows agent version `3.220.5`. Is it right that each time you run your pipeline, the agent creates a new `_work/X` folder (where `X` is some number)? If so, could you share a pipeline yml file example to reproduce this issue?

**Comment by DenisRumyantsev** [comment]
Hi, @Geo-Ron any updates about this issue?

**Comment by Geo-Ron** [comment]
> Hi @Geo-Ron, so, you are using self-hosted Windows agent version `3.220.5`. Is it right that each time you run your pipeline, the agent creates a new `_work/X` folder (where `X` is some number)? If so, could you share a pipeline yml file example to reproduce this issue?

Yes that is the case. A new `_work/X` folder and a complete download of the repository.

Example yml:

```yaml

# trigger:
# - main
trigger: none # Disable CI triggers.

pool: 'VDI Orchestrator'


parameters:
  - name: productDefinition
    type: string
    default: all
  - name: AutoAddDependencies
    type: boolean
    default: true

jobs:
  - job: processDefinition
    displayName: 'Process the Definitions'
    timeoutInMinutes: 360
    workspace: # Workspace options on the agent.
      clean: all
    steps:
    - task: PowerShell@2
      displayName: 'Read the Product Files'
      inputs:
        targetType: 'filePath'
        filePath: '$(System.DefaultWorkingDirectory)\current-method\pipelinescripts\Parse-Products.ps1'
        ${{ if ne(parameters.productDefinition, 'all') }}:
          arguments: '-Verbose -AutoAddDependencies:$${{parameters.AutoAddDependencies}} -imageDefinition ${{parameters.productDefinition}}'
        ${{ else }}:
          arguments: '-Verbose -AutoAddDependencies:$${{parameters.AutoAddDependencies}}'
        workingDirectory: '$(System.DefaultWorkingDirectory)\current-method\Definition-Products'
    - task: PowerShell@2
      displayName: 'Start the Build PipeLine'
      inputs:
        targetType: 'filePath'
        filePath: '$(System.DefaultWorkingDirectory)\current-method\pipelinescripts\Invoke-BuildPipeLine.ps1'
        arguments: '-Verbose'
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        PIPELINEBUILDS: $(pipelineBuilds)
        PRODUCT: $(product)

```

**Comment by DenisRumyantsev** [comment]
@Geo-Ron could you try to reproduce this issue using a simplified version of the pipeline, like this? —

```yml
trigger: none

pool: VDI Orchestrator

jobs:
- job: first_job
  displayName: First Job
  steps:
  - task: PowerShell@2
    displayName: First Step
    inputs:
      targetType: inline
      script: |
        Write-Host "Hello from the first step!"
  - task: PowerShell@2
    displayName: Second Step
    inputs:
      targetType: inline
      script: |
        Write-Host "Hello from the second step!"
```

**Comment by Geo-Ron** [comment]
I found new behaviour (or maybe I didn't look right in the first place).

On **any** change in the repository, the entire repository is (re-)downloaded...

I will try your yml file

**Comment by Geo-Ron** [comment]
With the provided yml file I observe the following:
- No extra folders being created (I have to check on the server itself)
- A complete repo download whenever more then one (1) change in the repo.

**Comment by DenisRumyantsev** [comment]
> A complete repo download whenever more than one (1) change in the repo.

@Geo-Ron, what do you mean by this? I tried to change and remove existing files, and add new files during the build, but the agent does not create a new `_work/X` folder after this. I was not able to reproduce this issue when I tried something like this:

```yml
trigger: none

pool: Self-Hosted Agent Pool

steps:
- bash: |
    echo "Create a new file" > "new-file.txt"
    echo "Edit an existing file" >> "first-existing-file.txt"
    rm "second-existing-file.txt"
```

Could you share a simple yml pipeline like this to reproduce this issue?
