### ISSUE TITLE
[enhancement]: _sigintTimeout should be modifiable by task creator or pipeline

### ISSUE THREAD

**Issue by steph409** [microsoft/azure-pipelines-agent#4364]
## _sigintTimeout should be modifiable by task creator or pipeline

Hi!

**Business case**
We are working successfully with Azure DevOps pipelines for multiple use cases. One use case is the rollout of infrastructure using terraform. Terraform has a graceful shutdown, when sigint is send. It stops to modify the resources in the cloud and updates the terraform state file, so that the configuration is consistent. After finishing the update, terraform releases the lock on the state file. When sigkill is send, the lock on the state file remains (and the state is not updated resulting in an inconsistent configuration). The next run will not work and the state lock will need to be removed manually. Terraform is quite slow, I would say it usually takes 10-30 seconds for the graceful shutdown depending on the size of the terraform configuration, with up to 1-2 minutes maybe as maximum.

**Current technical implementation**
When a pipeline is cancelled, Azure Devops does exactly what's expected.
[First send a sigint](https://github.com/microsoft/azure-pipelines-agent/blob/895e73a175bcca69e73da45542b58a8753bccf5d/src/Agent.Sdk/ProcessInvoker.cs#L455C11-L455C11), then wait for 7500ms. If the sigint has not finished by then, a sigkill is send. [The 7500ms is hardcoded in the code](https://github.com/microsoft/azure-pipelines-agent/blob/895e73a175bcca69e73da45542b58a8753bccf5d/src/Agent.Sdk/ProcessInvoker.cs#L34). This limit is not enough for e.g. terraform to do a graceful shutdown. [Here is an open issue from 2020](https://github.com/microsoft/azure-pipelines-terraform/issues/31) in the terraform task repository, pointing out this behavior.

**Possible implementation**
It would be great if the [hardcoded timeout](https://github.com/microsoft/azure-pipelines-agent/blob/895e73a175bcca69e73da45542b58a8753bccf5d/src/Agent.Sdk/ProcessInvoker.cs#L34) would be modifiable up to a certain hard upper limit, maybe 2 minutes or so. Either by the pipeline, which could increase this value, or, if you do not want this, maybe at least task creators could specify how long their graceful shutdown takes.

Best regards,
Stephi

**Comment by aleksandrlevochkin** [comment]
Hi @steph409, thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by peruzzof** [comment]
Hi, any update on this issue?

**Comment by Bouke** [comment]
This issue causes serious problems for us when using Terraform. We want to be able to cancel a pipeline, but it _SHOULD NOT_ terminate (sigkill) Terraform. Just ask it to stop nicely and that's it (sigint).

**Comment by steph409** [comment]
Hi @DenisNikulin5 ,

thanks for working on this issue. I am trying to understand if/how this works now.
I could not find it in the documentation, but I found [this issue ](https://github.com/microsoft/azure-pipelines-agent/issues/4317) describing how to set the KNOB settings.
I configured it as following:
<img width="539" alt="image" src="https://github.com/user-attachments/assets/530b20ca-085b-45f3-a76d-14327036db9f">


Then, I have a sample pipeline to test it. In this pipeline, I can see the first "initialize job" logs, where I can see some knob settings appear. Unfortunately, I can not see the values I configured on the agent.

<img width="848" alt="image" src="https://github.com/user-attachments/assets/597a5ed3-0bac-466d-ab55-72f9a4ee235a">


My test pipeline code is as following:
```yaml
pool:
  name: Azure Pipelines
  demands: PROCESS_SIGINT_TIMEOUT # exists check for custom PROCESS_SIGINT_TIMEOUT

stages:
  - stage: test
    jobs:
      - job: test
        steps:
          - task: Bash@3
            timeoutInMinutes: 1
            inputs:
              targetType: "inline"
              script: |
                trap 'echo signal int received!' SIGINT
                trap 'echo signal term received!' SIGTERM

                for i in `seq 300`
                do
                  echo $i
                  sleep 1
                done

            env:
              PROCESS_SIGINT_TIMEOUT: 30000
              PROCESS_SIGTERM_TIMEOUT: 30000
              USE_GRACEFUL_PROCESS_SHUTDOWN: true
```

To test the signals, I first trigger the pipeline, and then click on "cancel" while it is running. A sample output looks as following:

<img width="758" alt="image" src="https://github.com/user-attachments/assets/18706560-59eb-4665-8ac4-ed2b2e1a6575">



Now I am unsure if this should be working or what is still missing. From what I can see, there are also a couple of related issues open.

For example, the task lib seems to not pass down the SIGINT correctly: https://github.com/microsoft/azure-pipelines-task-lib/issues/858

Do you have a working sample for the changes you made and how to use them?

Ultimately, I want to use Azure DevOps to have Build-validation pipelines running for infrastructure (terraform) deployments. To allow automatic triggering, they need graceful shutdown, otherwise the terraform backend state will be broken.

Thanks for reading,
Stephi

**Comment by pszypowicz** [comment]
This is still a missing feature

**Comment by tarunramsinghani** [comment]
The capability of setting sigint timeout is already added via #4744 and can be used by setting following variables in pipelines

PROCESS_SIGINT_TIMEOUT
PROCESS_SIGTERM_TIMEOUT

Doc link on how to set pipeline variables - https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#specify-variables

**Comment by pszypowicz** [comment]
I was able to cancel my bash task with following code. It respected both timeouts and forwarded them to the bash task successfully. 

```
pool:
  name: Azure Pipelines

stages:
  - stage: test
    jobs:
      - job: test
        variables:
          - name: PROCESS_SIGINT_TIMEOUT
            value: 30000
          - name: PROCESS_SIGTERM_TIMEOUT
            value: 30000
        steps:
          - task: Bash@3
            timeoutInMinutes: 1
            inputs:
              targetType: "inline"
              script: |
                trap 'echo signal int received!' SIGINT
                trap 'echo signal term received!' SIGTERM

                for i in `seq 300`
                do
                  echo $i
                  sleep 1
                done
```

Adding `USE_GRACEFUL_PROCESS_SHUTDOWN` has some interesting consequences, because after initial sigint timeout, the logs are no longer shown in the web ui, and clearly task is still running in the background. 

After the task is finished, all logs from the step are not available in web ui.
