### ISSUE TITLE
[BUG]: Pipeline fails since upgrade to agent 3.227.2

### ISSUE THREAD

**Issue by Kralizek** [microsoft/azure-pipelines-agent#4472]
### What happened?

A pipeline started failing without any changes. These are the relevant parts of the pipeline.

```yaml
  - script: dotnet tool restore
    displayName: Restore tools
...
  - script: dotnet test backend/MySolution.sln --logger "junit;LogFilePath=$(Build.SourcesDirectory)/outputs/tests/{assembly}/TestResults.xml;MethodFormat=Full" --no-build --no-restore --collect:"XPlat Code Coverage" --results-directory "$(Build.SourcesDirectory)/outputs/coverage"
    displayName: Run tests
...
  - script: dotnet coverage merge outputs/coverage/ -r -f cobertura -o $(coverageFilePath)
    displayName: Merge coverage files
```

Here is the dotnet-tools.json file

```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-coverage": {
      "version": "17.8.6",
      "commands": [
        "dotnet-coverage"
      ]
    }
  }
}
```

Here is the relevant output on the pipelines:

```
Starting: Restore tools
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.229.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
dotnet tool restore
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/3194b80f-5743-47cf-9f3e-82b8450a245e.sh
Skipping NuGet package signature verification.
Tool 'dotnet-coverage' (version '17.8.6') was restored. Available commands: dotnet-coverage

Restore was successful.
Finishing: Restore tools
```

```
Starting: Run tests
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.229.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
dotnet test backend/MySolution.sln --logger "junit;LogFilePath=/home/vsts/work/1/s/outputs/tests/{assembly}/TestResults.xml;MethodFormat=Full" --no-build --no-restore --collect:"XPlat Code Coverage" --results-directory "/home/vsts/work/1/s/outputs/coverage"
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/2c32f82d-4c69-491b-a7b3-2a1137680838.sh

[...]

Attachments:
  /home/vsts/work/1/s/outputs/coverage/a9a1ad8e-9c1a-4015-bea8-db6028dd1390/coverage.cobertura.xml
  /home/vsts/work/1/s/outputs/coverage/d0960b3d-8718-409a-b095-d4ca80346951/coverage.cobertura.xml
Finishing: Run tests
```

```
Starting: Merge coverage files
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.229.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
dotnet coverage merge outputs/coverage/ -r -f cobertura -o outputs/coverage/cobertura.xml
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/2006242c-3ddd-47a5-a891-f25d4a750dae.sh
Run "dotnet tool restore" to make the "dotnet-coverage" command available.
##[error]Bash exited with code '1'.
Finishing: Merge coverage files
```

### Versions

Looking at the pipeline logs, I noticed that the agent version changed from 3.277.1 (working) to 3.277.2 (broken).

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)
