### ISSUE TITLE
[BUG]: autoCancel is ignored in pr trigger and new builds are triggered

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/azure-pipelines-agent#4523]
### What happened?

I wrote pr trigger with autoCancel set to false, created PR and tried do another commit to test if autoCancel will work, but in PR has been triggered another set of builds and previous has been cancelled

### Versions

Azure DevOps online, Windows 11 Canary, on Azure DevOps used hosted windows version in pipelines

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11

### Version controll system

git

**Comment by ismayilov-ismayil** [comment]
Hi @JanRajnoha, thanks for reporting.
Could you please explain issue a bit more?
Is this possible to share pipeline yaml file and agent log with system.debug enabled? (please consider to remove or mask confidential data)

**Comment by JanRajnoha** [comment]
No problem.

in yaml i have this (for triggers):
```
trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - list-of-paths

pr:
  autoCancel: false
  branches:
    include:
    - '*'
  paths:
    include:
    - list-of-paths
``` 

and from pipeline: 
##[error]The build was canceled by Microsoft.VisualStudio.Services.TFS.
