### ISSUE TITLE
[BUG]: YAML literal date variables are parsed as date

### ISSUE THREAD

**Issue by qetza** [microsoft/azure-pipelines-agent#4530]
### What happened?

Hi,
When defining variable values in YAML that that represents literal dates those values are always parsed as datetime instead of being left as strings so the value is not the one expected. This does not happen with variable group values.

Example of YAML build:
```yaml
pool:
  vmImage: ubuntu-latest

trigger: none

variables:
- name: dateWithoutQuotes
  value: 2020-01-01T22:32:00Z
- name: dateWithSingleQuotes
  value: '2020-01-01T22:32:00Z'
- name: dateWithDoubleQuotes
  value: "2020-01-01T22:32:00Z"
- name: dateWithExplicitType
  value: !!str 2020-01-01T22:32:00Z
- group: "issue-325"

steps:
- pwsh: 'gci env:'
  displayName: dump env
```

The variable group `issue-325` has the following variables:
![image](https://github.com/microsoft/azure-pipelines-agent/assets/8191369/d0095a6e-be8c-4814-ae4f-01b6dc1fb8ab)

Here is the output of the task dumping the environment variables with the variable values:
![image](https://github.com/microsoft/azure-pipelines-agent/assets/8191369/38e681c2-1e88-4b69-af32-95530ab0b0cd)

As you can see only the variable from the variable group has kept it's original value all others were parsed as datetime even though the values are quoted or explicitly set as string.

This is making issues with the users of my task `replace tokens` (issues https://github.com/qetza/vsts-replacetokens-task/issues/325 and https://github.com/qetza/vsts-replacetokens-task/issues/176)

Is there any way to force the string value (no parsing) or is this an issue in the agent when reading YAML variables?

Thanks

### Versions

Azure DevOps Services

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu Latest

### Version controll system

Azure Git Repository
