### ISSUE TITLE
[Question]: Can we configure number of repo clones in self-hosted agent

### ISSUE THREAD

**Issue by nishanthpasham** [microsoft/azure-pipelines-agent#4624]
### Describe your question

We're running self-hosted Azure agents for our CIs. Our codebase is big ~30GB. By default, looks like the agent can clone the code up to 6 times, while running different jobs. When this happens, we are running out of disk space on our CI VM. 

Ideally we'd like to configure the max number of code clones when setting up the self-hosted agent. Is there a way to specify this?

![image](https://github.com/microsoft/azure-pipelines-agent/assets/11204601/a0dc71af-7004-456b-b2f9-fa30e51d11b5)

### Versions

agent v3.232.1 

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Rocky Linux 9.3

### Version controll system

git

**Comment by aleksandrlevochkin** [comment]
Hi @nishanthpasham, thank you for your question. You can use the pipeline variable `AZP_AGENT_ALLOW_WORK_DIRECTORY_REPOSITORIES` to clone the code to a common location in the work directory.

**Example - test1.yml:**

 ```yaml
trigger:
- main

pool: 'Default'

variables:
  AZP_AGENT_ALLOW_WORK_DIRECTORY_REPOSITORIES: "true"

jobs:
- job: Test1
  steps:
  - checkout: self
    path: ../repos/test
  - script: echo Test2
```

**Example - test2.yml:**

```yaml
trigger:
- main

pool: 'Default'

variables:
  AZP_AGENT_ALLOW_WORK_DIRECTORY_REPOSITORIES: "true"

jobs:
- job: Test2
  steps:
  - checkout: self
    path: ../repos/test
  - script: echo Test2
```

In this case, the repository for both build definitions will be placed in the same directory (`_work\repos\test`), not taking up additional disk space.
