### ISSUE TITLE
[BUG]: variables substitution for container jobs resolves to agent-job paths

### ISSUE THREAD

**Issue by ThijsBroersen** [microsoft/azure-pipelines-agent#4625]
### What happened?

I tried adding variables via a template, e.g. 
```
- job: myjob
  container: mycontainer
  variables:
    - template: myvars.yml
```

Within myvars.yml I am trying to get `$(Pipeline.Workspace)`, but this resolves to `/agent/_work/1` instead of the expected `/__w/1` for a container job. 

### Versions

latest ubuntu

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)
