### ISSUE TITLE
Set the working directory across a stepList parameter or across a full job 

### ISSUE THREAD

**Issue by dayinsure-devops** [microsoft/azure-pipelines-agent#4642]
### Describe your question

I have a job template with some `stepList` parameters for providing additional steps before and after the core logic of the job. In this job I have had to checkout the repo containing the templates itself and the target repo (`self`). This alters the default working directory so that it is no longer in the root of the target repo, but instead it is one navigation backwards where both repos are cloned. This has breaking change implications for users of the template unless the pathing is modified to account for this across all steps in the job. The job that I am specifically referring to in this case is for building a docker image, therefore this can be resolved quite easily by prefixing the `dockerfile` and `dockerBuildContext` options with $(Build.Repository.Name). However, the job also has a `preBuildSteps` parameter of type `stepList`. I cannot find a way to modify the working directory of all steps within this stepList. I have tried:

1. Surrounding the `stepList` with two bash tasks doing a `pushd $(Build.Repository.Name)` and then a `popd`. But it seems that this directory change is not preserved across steps
2. Overriding the `SYSTEM_DEFAULTWORKINGDIRECTORY` environment variable at the job level in an effort to change the working directory of all tasks. This didn't seem to work but anyway I'd also have concerns over how this might affect the checkout steps.

The unmodified template yaml is as follows:
```yaml
jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.displayName }}
    ${{ if parameters.dependsOn }}:
      dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    ${{ if parameters.condition }}:
      condition: ${{ and(succeeded(), parameters.condition) }}
    ${{ if parameters.reposReferenced }}:
      uses: 
        repositories: ${{ parameters.reposReferenced }}
    variables:
      - name: DOCKER_BUILDKIT
        value: 1
      - template: ../vars/docker-registry.yml
    steps:
      - checkout: self
        submodules: '${{ parameters.checkoutSubmodules }}'
      - checkout: ${{ parameters.thisRepoResourceName }}
      - ${{ if gt(length(parameters.extraPreBuildSteps), 0) }}:
          - ${{ parameters.extraPreBuildSteps }}
      - template: ../steps/docker-login.yml
        parameters:
          containerRegistryServiceConnection: ${{ variables.containerRegistryServiceConnection }}
      - ${{ each layer in parameters.layersToBuild }}:
        - ${{ if layer.preBuildSteps }}:
          - ${{ layer.preBuildSteps }}
        - template: ../steps/docker-build.yml
          parameters:
            displayName: build image ${{ layer.name }}
            dockerRepository: ${{ parameters.dockerRepository }}
            dockerfile: ${{ parameters.dockerfile }}
            dockerBuildContext: ${{ parameters.dockerBuildContext }}
            target: ${{ layer.name }}
            dockerBuildArgs: ${{ parameters.dockerBuildArgs }}
            tags: ${{ parameters.version }}
        - template: ../steps/get-image-name.yml
          parameters:
            dockerRepository: ${{ parameters.dockerRepository }}
            layer: ${{ layer.name }}
            imageTag: ${{ parameters.version }}
            outputVariableName: imageName
        - template: ../steps/docker-save.yml
          parameters:
            displayName: save image ${{ layer.name }}
            outputLocation: '$(Pipeline.Workspace)/${{ layer.imageTarName }}.tar'
            imageToSave: '${{ variables.containerRegistry }}/$(imageName):${{ parameters.version }}'
        - task: PublishPipelineArtifact@1
          displayName: publish image ${{ layer.name }}
          inputs:
            targetPath: '$(Pipeline.Workspace)/${{ layer.imageTarName }}.tar'
            artifactName: ${{ layer.imageArtifactName }}
        - ${{ if layer.postBuildSteps }}:
            - ${{ layer.postBuildSteps }}
      - ${{ if gt(length(parameters.extraPostBuildSteps), 0) }}:
        - ${{ parameters.extraPostBuildSteps }}
```

My problem is that the user of this template shouldn't have to be aware of directory changes.

### Versions

Dev19.M233.1 (AzureDevOps_M233_20240205.3) / ubuntu-latest

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest
