### ISSUE TITLE
[BUG]: Build randomly cancels due to agent issue

### ISSUE THREAD

**Issue by TheAnarchoX** [microsoft/azure-pipelines-agent#4707]
### Describe your question

We've been seeing random occurrences of build jobs cancelling themselves on one of our docker build tasks, it appears to hang for a long time and than it just cancels its tasks with this appearing in the stage view, note: this message disappears on reload:

```
##[error]The hosted runner encountered an error while running your job. (Error Type: Disconnect).
Pool: Azure Pipelines
Image: ubuntu-latest
Queued: Today at 11:39 [manage parallel jobs]
Agent: Hosted Agent
Started: Today at 11:40
Duration: 24m 55s

The agent request is already running or has already completed.
Job preparation parameters
Job live console data:
Starting: Build
##[debug]Agent environment resources - Unable to get disk info, exception: Value cannot be null. (Parameter 'driveName'), Memory: Used 506.00 MB out of 6921.00 MB, CPU: Usage 96.41%
##[debug]Cleaning agent temp folder: /home/vsts/work/_temp
##[debug]Skipping overwrite %TEMP% environment variable
Async Command Start: DetectDockerContainer
Async Command End: DetectDockerContainer
Async Command Start: DetectDockerContainer
Async Command End: DetectDockerContainer
```

When this task is cancelled this is what is shown in the logs of the task itself:

`Nothing to show. Final logs are missing. This can happen when the job is cancelled or times out.`

Task info:
```
Task         : Docker
Description  : Build or push Docker images, login or logout, start or stop containers, or run a Docker command
Version      : 2.231.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-tsg

```

Pipeline yaml:

```
trigger:
  - develop
  - staging
  - main

resources:
  - repo: self

variables:
  - ${{ if eq(variables['build.SourceBranchName'], 'develop') }}:
    - group: redacted
  - ${{ if eq(variables['build.SourceBranchName'], 'staging') }}:
    - group: redacted
  - ${{ if eq(variables['build.SourceBranchName'], 'main') }}:
      - group: redacted
  - name: BUILD_ID
    value: $(Build.BuildId)-$(Build.SourceBranchName)
  - name: imageRepository
  - name: dockerRegistry
    value: "redacted"
  - name: imageRepository
    value: "redacted"
  - name: dockerfilePath
    value: "$(Build.SourcesDirectory)/Dockerfile"
  - name: vmImageName
    value: "ubuntu-latest"
  - name: system.debug
    value: true

stages:
  - stage: Build
    displayName: Build Frontend

    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)

        steps:
          - task: DownloadSecureFile@1
            inputs:
              secureFile: ".env.frontend"
          - bash: |
              mv $(Agent.TempDirectory)/.env.frontend $(Agent.TempDirectory)/.env
            displayName: "Rename .env.frontend to .env"

          - task: CopyFiles@2
            inputs:
              SourceFolder: "$(Agent.TempDirectory)"
              Contents: ".env"
              TargetFolder: "$(Build.SourcesDirectory)"

          - task: EnvTransform@0
            inputs:
              inputType: "file"

          - task: npmAuthenticate@0
            inputs:
              workingFile: ".npmrc"

          - task: Docker@2
            inputs:
              command: "build"
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistry)
              arguments: --build-arg NODE_ENV=$(NODE_ENV)
              Dockerfile: $(dockerfilePath)
              tags: |
                $(Build.BuildId)-$(Build.SourceBranchName)
                latest-$(Build.SourceBranchName)
            displayName: "Build Dockerfile"
            enabled: true

          - task: Docker@2
            inputs:
              command: "push"
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistry)
              tags: |
                $(Build.BuildId)-$(Build.SourceBranchName)
                latest-$(Build.SourceBranchName)
            displayName: "Push to altura.azurecr.io"
            enabled: true

          - task: PublishBuildArtifacts@1
            displayName: "Upload Artifacts"
            inputs:
              pathtoPublish: "$(Build.ArtifactStagingDirectory)"
              artifactName: "drop"
```

Dockerfile:

```
FROM node:20

ARG NODE_ENV

ENV HOST=0.0.0.0
ENV NODE_ENV=$NODE_ENV
ENV NODE_OPTIONS=--max-old-space-size=16384
ENV CI=1

# Create app directory
WORKDIR /app
ADD . /app/

# Global install & build
RUN npm install --include dev

# remove all translations
RUN rm -rf ./translations/*
RUN npm run translations
RUN npm run build

EXPOSE 3000

# Start command
CMD [ "node", ".output/server/index.mjs" ]
```

### Versions

Agent Version: 3.236.1
Image: ubuntu-latest

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

### Version controll system

git
