### ISSUE TITLE
[BUG]: Build breaks with ENOBUFS error after successful Java unit tests

### ISSUE THREAD

**Issue by schuettecarsten** [microsoft/azure-pipelines-agent#4767]
### What happened?

Build breaks with ENOBUFS error after successful Java unit tests. The Java build step works fine on a local machine. Tests are also executed sucessfully on the agent VM. The VM has 8 Cores and 16 GB RAM which should be more than enough, memory/CPU limites are not reached at all.

### Versions

3.238.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Version controll system

git

### Relevant log output

```shell
[...]

nsctestsupport_jacocoreport:
[jacoco:report] Loading execution data file /home/azureuser/myagent/_work/1/s/core-customize/hybris/log/junit/jacoco.exec
[jacoco:report] Writing bundle 'JaCoCo' with 1134 classes

BUILD SUCCESSFUL
Total time: 3 seconds

BUILD SUCCESSFUL in 1m 31s
2 actionable tasks: 2 executed

##[error]Unhandled: write ENOBUFS
##[error]Error: write ENOBUFS
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writevGeneric (node:internal/stream_base_commons:143:3)
    at Socket._writeGeneric (node:net:950:11)
    at Socket._writev (node:net:959:8)
    at doWrite (node:internal/streams/writable:588:12)
    at clearBuffer (node:internal/streams/writable:765:5)
    at onwrite (node:internal/streams/writable:644:7)
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:106:10)
Finishing:  Unittest
```

**Comment by schuettecarsten** [comment]
The build setup:

```
  - task: Gradle@3
    displayName: ' Unittest'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'unittest'
      options: '-PbuildConfigHybris=$(hybris.config.environment)'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false      
 ```
