### ISSUE TITLE
[enhancement]: Option or knob to control checkout behavior when same repository is specified twice

### ISSUE THREAD

**Issue by lettucemode** [microsoft/azure-pipelines-agent#4815]
### Describe your feature request here

We have a script that we run against each repo in a microservice system on a nightly basis. Each repo is checked out in to the default `s/` dir, then a script iterates over each folder in `s/` to do its work. The pipeline takes this form:

```yaml
steps:
- checkout: git://my-project/repo-1
- checkout: git://my-project/repo-2
# more checkout steps omitted
- bash: |
    cd $(Build.SourcesDirectory)
    for D in $(find . -mindepth 1 -maxdepth 1 -type d -exec realpath {} \;); do
      cd $D
      # do stuff in directory D
    done
```

I am working on adding additional branches beyond the default to this. I tried this:
```yaml
steps:
- checkout: git://my-project/repo-1
- checkout: git://my-project/repo-1@other-branch
  path: s/repo-1-other
- checkout: git://my-project/repo-2
- checkout: git://my-project/repo-2@other-branch
  path: s/repo-2-other
# etc
```

However, in this case `checkout` will [move the already-checked-out repository to the new path](https://github.com/microsoft/azure-pipelines-agent/blob/4c7bc633572b50c0ee2e0b218805563cdc7979ea/src/Agent.Plugins/RepositoryPlugin.cs#L190) and then fetch the specified branch. So in the above example, the first `checkout` step for repo-1 becomes superfluous because that directory doesn't exist anymore after the second one. This isn't what I want. I want one folder in `s/` per checkout step, even if they are from the same repo. This way the existing script can continue to work on a folder-by-folder basis without modifications.

If a knob or setting already exists for this, please let me know what it is, otherwise I am requesting one. Thanks for your consideration.

**Comment by DmitriiBobreshev** [comment]
Hi @lettucemode, Thanks for the idea! As far as I know, we don't have such knobs to control the behaviour. We'll try to implement it in the future, but now we have more prioritized items.

**Comment by lettucemode** [comment]
So after some experimentation and digging through the source, it turns out the behavior I want is already present. The two different refs of the repository need to have different aliases (the names that they are referred to in the rest of the YAML) and different paths specified. If a repository resource is not used and you use the shorthand instead, the alias includes the `@ref` at the end.

Here's the verbose way to do it:
```
resources:
  repositories:
  - repository: repo-1-main
    type: git
    name: my-project/repo-1
    ref: main
  - repository: repo-1-other
    type: git
    name: my-project/repo-1
    ref: other
  - repository: repo-2-main
    type: git
    name: my-project/repo-2
    ref: main
  - repository: repo-2-other
    type: git
    name: my-project/repo-2
    ref: other

steps:
- checkout: repo-1-main
  path: s/repo-1-main
- checkout: repo-1-other
  path: s/repo-1-other
- checkout: repo-2-main
  path: s/repo-2-main
- checkout: repo-2-other
  path: s/repo-2-other
```
Or, with the shorthand:
```
steps:
- checkout: git://my-project/repo-1@main
  path: s/repo-1-main
- checkout: git://my-project/repo-1@other
  path: s/repo-1-other
- checkout: git://my-project/repo-2@main
  path: s/repo-2-main
- checkout: git://my-project/repo-2@other
  path: s/repo-2-other
```
It's a little odd that omitting the `@ref` from the shorthand (as in my first post above) causes the overwriting behavior - I expected it could infer the different branch name, but I guess it's fine. My solution isn't that much more verbose to warrant a change, imo anyway.
