### ISSUE TITLE
[enhancement]: Add localImage option for job containers

### ISSUE THREAD

**Issue by npalmius** [microsoft/azure-pipelines-agent#5014]
### Describe your feature request here

When specifying a container in a resource, (e.g. [resources.containers.container](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-containers-container?view=azure-pipelines)) there is a `localImage` option to use locally cached images rather than pulling from the repository (we are using self-hosted agents, so we pull the images that we need locally when building the agent).

However, we are using a lot of nested templates in our setup, so we define the container directly in the job (e.g. using a [jobs.job.container: image](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job-container?view=azure-pipelines#container-image) definition).

This definition does not have all of the options from the resources.containers.container definition, and in particular the `localImage` option.

Would it be possible to add the ability to specify the `localImage` option in job container objects?

**Comment by vmapetr** [comment]
Hi @npalmius, thank you for reporting this issue!
Could you please share more details? 
What value do you use for the `localImage`? Please consider that this is boolean parameter which can take only true or false value.

**Comment by npalmius** [comment]
Hi @vmapetr,

Thanks for replying, and apologies for the delay in getting back to you. Agree that the original issue probably wasn't as clear as it could have been.

In a standalone pipeline, we can use this:
```yaml
resources:
  containers:
    - container: pipelineContainer
      image: our_repo.com/some_pipeline_container:latest
      localImage: true

stages: 
- stage: build
  jobs:
    - job: build
      container: pipelineContainer
      steps:
        ...
```

However, we have many pipelines using shared templates, e.g.:

```yaml
resources:
  repositories:
    - repository: templates
      type: git
      name: Shared Build Templates/templates

extends:
  template: build.yml@templates
```

In this case, the `build.yml` shared template cannot define `resources`, so we define the pipeline container in the job as follows:

```yaml
parameters:
- name: param
  type: string 
  default: ''

stages: 
- stage: build
  jobs:
    - job: build
      container:
        image: our_repo.com/some_pipeline_container:latest
      steps:
        ...
```

The request is to be able to define `localImage` in the job container without needing to define a container resource.
